config/routes.rb
Rails.application.routes.draw do

  get 'item_cost_analysis_reports/index'

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords" }
  resources :company_users, controller: "users"
  root 'pages#index'
  get 'dashboard' => 'dashboard#index'
  get 'purchase_listings' => 'reports#purchase_listings'
  get 'purchase_summary' => 'reports#purchase_summary'
  get 'item_purchase_detail' => 'reports#item_purchase_detail'
  get 'price_movement_report' => 'reports#price_movement_report'
  get 'invoice_entry_report' => 'reports#invoice_entry_report'
  get 'update_item' => 'reports#update_item'
  get 'man_hours' => 'reports#man_hours'
  resources :reports, only: [] do
    get :get_purchased_items_per_item, on: :collection
  end
  get 'profit_and_losses' => 'profit_and_losses#index'
  get 'settings' => 'settings#index'
  patch 'update_settings' => 'settings#update_settings'
  patch 'csrab' => 'settings#csrab'
  get 'account/:username' => 'users#account', as: 'account', :constraints => { :username => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ }
  patch 'account/:username/update_account' => 'users#update_account', as: 'update_account'
  patch 'account/:username/change_password' => 'users#change_password', as: 'change_password'
  resource :client, only: [:show, :edit, :update]
  resources :timesheets do
    get :get_branch, on: :collection
    get :get_branch_employees, on: :collection
    get :show_holiday, on: :collection
    get :get_timesheets, on: :collection
    get :export_timesheets, on: :collection
    post "update_timesheets" => "timesheets#update_timesheets"
  end
  resources :employee_benefits
  resources :holidays
  resources :tax_types
  #resources :timesheet_fields
  resources :brands do
    resources :branches
    get :set_purchase_order_restriction, on: :collection
    get :setup_branch_po_setup, on: :collection
    post :create_branch_po_setup, on: :collection
    put :update_branch_po_setup, on: :collection
    get :update_po_schedule, on: :collection
    get :admins_privileges, on: :collection
    post :update_po_privilege, on: :collection
    post :create_purchase_order_setting, on: :collection
    put :update_purchase_order_setting, on: :collection
  end
  resources :roles do
    get 'manage_permissions' => 'permissions#index'
    put 'manage_permissions' => 'permissions#update'
  end
  resources :employees do
    get 'labor_hours' => 'employees#labor_hours'
    get "add_timesheets" => 'employees#add_timesheets'
    put "save_timesheets" => 'employees#save_timesheets'
    get "download_timesheet" => 'employees#download_timesheet'
  end
  resources :labor_hours do
    get 'work_hours_list' => 'labor_hours#work_hours_list'
  end
  resources :settlements
  resources :categories do
    get 'new_subcategory' =>'categories#new_subcategory'
  end
  resources :item_cost_analysis_reports
  resources :shifts, only: [:index,:create,:update,:destroy]
  resources :sales do
    get :confirm, on: :collection
    get "email_form" => "sales#email_form"
    get :sales_setup, on: :collection
    post "send_sale_details" => "sales#send_sale_details"
    post :save_setup, on: :collection
  end
  resources :units
  resources :items
  resources :inventories
  resources :employee_types
  resources :conversions
  resources :suppliers
  resources :manifolds
  resources :directionals
  resources :sale_reports, only: :show
  resources :purchases do
    resources :purchase_items
    get :purchase_order_lookup, on: :collection
    post :purchase_create, on: :collection
    get :purchase_new_record, on: :collection
    post :create_purchase_items, on: :collection
    get "add_purchase_item" => "purchases#add_purchase_item"
    get :edit_purcahse_limit, on: :collection
    post :limit_edit, on: :collection 
    get "view_history_log" => "purchases#view_history_log"
  end
  resources :subscriptions do
    get 'show_branches', on: :collection
    get 'subscribe', on: :collection
  end

  resources :purchase_order_generator, only: [:index, :new] do
    get :get_pos, on: :collection
  end
  resources :bills
  resources :payment_notifications
  post 'paypal_checkout' => 'subscriptions#paypal_checkout'
  get 'process_subscription' => 'subscriptions#process_subscription'
  get 'update_subscription' => 'subscriptions#update_subscription'
  delete 'subscription/:id/cancel', to: 'subscriptions#cancel', as: 'cancel_subscription'
  
  resources :purchase_orders_summary, only: :index 
  resources :purchase_orders_listing, only: :index
  resources :supplier_item_prices
  resources :order_per_suppliers
  resources :order_lists do
    get 'update_status' => 'order_lists#update_status'
  end
  resources :purchase_orders do
    resources :purchase_order_items do
      get :send_email, on: :collection
      get :approve_purchase_order, on: :collection
    end
    get :view_po_remotely, on: :collection
    get :send_bulk_purchase_orders, on: :collection
    get :group_of_purchase_orders, on: :collection
    get :purchase_orders_per_supplier, on: :collection
    get :hold_po, on: :collection
    patch :reject_selected_purchase_orders, on: :collection
    post :mail_bulk_of_purchase_orders, on: :collection
    post 'send_email_notification' => 'purchase_orders#send_email_notification'
    patch 'approve' => 'purchase_orders#approve'
    patch 'hold' => 'purchase_orders#hold'
    patch 'reject' => 'purchase_orders#reject'
    get 'purchase_order' => 'purchase_orders#purchase_order'
    get 'edit_delivery_details' => 'purchase_orders#edit_delivery_details'
    put 'update_delivery_details' => 'purchase_orders#update_delivery_details'
    patch 'save_po_items' => 'purchase_orders#save_po_items'   
  end

  #resources :revenues_setup, as: :revenues
  resources :statistics_setup, as: :statistics
  resources :non_miscellaneous_setup, as: :non_misces
  
  resource :wizard, only: [:show] do
    get 'user_setup' => 'wizards#user_setup'
    get 'company_setup' => 'wizards#company_setup'
    get 'brand_setup' => 'wizards#brand_setup'
    get 'branch_setup' => 'wizards#branch_setup'
    get 'setup_summary' => 'wizards#setup_summary'
    put 'user_setup_complete' => 'wizards#user_setup_complete'
    put 'company_setup_complete' => 'wizards#company_setup_complete'
    put 'brand_setup_complete' => 'wizards#brand_setup_complete'
    put 'branch_setup_complete' => 'wizards#branch_setup_complete'
    put 'setup_summary_complete' => 'wizards#setup_summary_complete'
  end

  get 'directionals/search' => 'directionals#search_entry'

  # ajax
  get 'update_role' => 'pages#update_role'
  get 'update_branch' => 'pages#update_branch'
  get 'update_units' => 'pages#update_units'
  get 'update_price' => 'pages#update_price', as: 'price'
  get 'registration_validate_email' => 'pages#registration_validate_email'
  get 'registration_validate_username' => 'pages#registration_validate_username'
  get 'new_password_validate_email' => 'pages#new_password_validate_email'
  put 'change_brand' => 'pages#change_brand'
  get 'get_plan_info' => 'pages#get_plan_info'
  get 'get_total_amount' => 'pages#get_total_amount'
  get 'get_price' => 'pages#get_price'
  get 'get_units' => 'pages#get_units'
  get 'take_units' => 'pages#take_units'
  get 'validate_time' => "pages#validate_time"
  

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy', as: :logout
    resources :clients do
      get :all_non_subscribers, on: :collection
      get :subscribers, on: :collection
      get :new_clients, on: :collection
      post :subscribe_branches, on: :collection
      get :show_branch_subscriptions, on: :collection
      get "get_total_amount" => "clients#get_total_amount"
      get "get_plan_info" => "clients#get_plan_info"
      post "create_subscription" => "clients#create_subscription"
      post :remove_selected_branches, on: :collection
      post :resubscribe_branches, on: :collection
      get :get_subscription, on: :collection
      post :update_subscription, on: :collection
    end
  end

  namespace :api do
    resources :sales, only: :index do
      get :get_sales_averages, on: :collection
      get :get_customer_count, on: :collection
      get :get_average_revenues, on: :collection
      get :get_sales_per_week, on: :collection
      get :get_sales_per_month, on: :collection
    end

    resources :users, only: :index do
      get :users_per_branch, on: :collection
      get :users_per_brand, on: :collection
    end

    resources :reports, only: :index do
      get :get_invoices, on: :collection
    end

    resources :dashboards, only: :index do
      get :this_week_sales_vs_expense, on: :collection
      get :this_years_sales_expense, on: :collection
      get :monthly_sales_average, on: :collection
      get :monthly_customer_count_average, on: :collection
      get :this_year_total_sales, on: :collection
      get :get_branches_ranking, on: :collection
      get :price_movement, on: :collection
    end

    resources :purchase_order_summary, only: :index do
      get :get_purchase_orders, on: :collection
      get :get_on_hold_pos, on: :collection
      get :get_rejected_pos, on: :collection
    end

    resources :purchase_orders, only: :index do
      get :get_pos, on: :collection
      get :summary, on: :collection
    end

    resources :purchases, only: :index do
      get :searched_purchases, on: :collection
      get :export_excel, on: :collection
      get :default_excel, on: :collection
      get :purchased_items, on: :collection
      get :get_pos_for_purchasing, on: :collection
    end

    resources :item_and_costs, only: :index do
      get :filtered_records, on: :collection
      get :this_month_for_brand_admin, on: :collection
      get :this_week_for_brand_admin, on: :collection
      get :this_month_for_branch_admin, on: :collection
      get :this_week_for_branch_admin, on: :collection

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
	before_action :authenticate_user!
	before_action :access_control
	before_action :set_brand
	before_action :set_branch, only: [:show, :edit, :update, :destroy]

	def show
	end

	def new
		@branch = Branch.new
	end

	def create
		@branch = @brand.branches.new(branch_params)
		if @branch.save
			flash[:notice] = "Branch successfully created"
		else
			flash[:alert] = @branch.errors.full_messages.join(", ")
		end
		redirect_to brand_path(id: @brand.id, brand_pane: true)
	end

	def update
		if @branch.update(branch_params)
			flash[:notice] = "Branch successfully updated"
		else
			flash[:alert] = @branch.errors.full_messages.join(", ")
		end
		redirect_to brand_path(id: @brand.id, brand_pane: true)
	end

	def show
		
	end

	def destroy
		begin
			@branch.destroy
			redirect_to brand_path(id: @brand.id, brand_pane: true), notice: "Branch successfully deleted"
		rescue ActiveRecord::InvalidForeignKey => e
			errors = []
			errors << "An unkonwn reason ( please kindly report to the developers for immediate fixing )" if errors.empty?
			puts e if errors.empty?
      redirect_to brand_path(id: @brand.id, brand_pane: true), alert: "You cannot delete #{@branch.name} because of the following #{'reason'.pluralize(errors.count)}: #{errors.join('; ')}"
    end
	end

	private

	def set_brand
		@brand = current_client.brands.friendly.find(params[:brand_id])
	end

	def set_branch
		@branch = @brand.branches.find(params[:id])
	end

	def branch_params
		if params["colorpicker-option-selected"]
			params[:branch][:color] = params["colorpicker-option-selected"]
		end
		params.require(:branch).permit(:name, :branch_type, :tin_number, :company_registered_name, :aka, :address1, :brand_id, :color, :city, :zip, :email_address, :landline_no, :mobile_no, :fax_no, :delivery_time, branch_tax_attributes: [ :id, :branch_id, :tax_type_id ])
	end
end

app/views/branches/_form.html.slim
= form_for [@brand, @branch] do |f|
  .row
    .col-xs-6.mb10
      = f.label :name
        | Branch
        small.field-req  *
      = f.text_field :name, class: "form-control", placeholder: "Name"
    .col-xs-6.mb10
      = f.label 'Alias'
        | Alias
        small.field-req  * <i>No spaces please</i>
      = f.text_field :aka, class: "form-control", placeholder: "Alias: e.g 'Br', 'BR', 'Bwnt'"
    .col-xs-12.mb10
      = f.label :color
        | Color
        small.field-req  *
      br
      = f.select :color, [["#1E81B4","#1E81B4"],["Coral","#E26A6A"],["Pumpkin","#FF4500"],["#DC143C","#DC143C"],["#FF8C00","#FF8C00"],["#C71585","#C71585"],["Eggplant","#60355B"],["#00A087","#00A087"],["#DD525B","#DD525B"],["#8CAF41","#8CAF41"],["#8F7260","#8F7260"],["#4F669D","#4F669D"],["#646464","#646464"],["#AAA786","#AAA786"],["#6F9684","#6F9684"],["#98ACD1","#98ACD1"]], {}, name: "colorpicker-option-selected", id: "init"
    .col-xs-12.mb10
      = f.label :address1, "Address"
      = f.text_area :address1, placeholder: "Address of Branch", rows: 2, class: "form-control"
    
    .col-xs-6.mb10
      = f.label :tin_number
        | Tin Number
        small.field-req  *
      = f.text_field :tin_number, class: "form-control"
    
    .col-xs-6.mb10
      = f.label :company_registered_name
        | Company Registered Name
        small.field-req  *
      = f.text_field :company_registered_name, class: "form-control"
    
    .col-xs-6.mb10
      = f.label :city
      = f.text_field :city, class: "form-control"
    .col-xs-6.mb10
      = f.label :zip
        | Zip
        a data-original-title="What's my zip?" data-placement="top" data-tt="tooltip" href="http://zip-codes.philsite.net/" target="_blank"
          text-grey  ?
      = f.number_field :zip, class: "form-control"
    .col-xs-4.mb10
      = f.label :email_address
        | E-mail Address
        small.field-req  *
      = f.text_field :email_address, class: "form-control", placeholder: "E-mail address of branch"
    .col-xs-4.mb10
      = f.label :branch_type
        | Branch Type
        small.field-req  *
      = f.select :branch_type, [["Company Own","company_own"],["Franchise","franchise"]], { include_blank: true }, class: "chosen", data: { placeholder: "Type of branch" }, style: "width: 100%;"

    = f.fields_for :branch_tax, @branch.branch_tax || @branch.build_branch_tax do |b|
      .col-xs-4.mb10
        = b.label :tax_type_id
          | Tax Type
          small.field-req  *
        = b.select :tax_type_id, current_brand.tax_types.pluck(:name, :id), { include_blank: true }, class: "chosen", data: { placeholder: "Select" }, style: "width: 100%;"
    /.col-xs-6.mb10
      = f.label :delivery_time
        | Delivery Time
        small.field-req  * <i>For Purchasing Purposes</i>
      input.form-control type='time' name='branch[delivery_time]' id='delivery_time'         

    .col-xs-12.col-lg-4.mb10
      = f.label :landline_no
      = f.number_field :landline_no, class: "form-control"
    .col-xs-12.col-lg-4.mb10
      = f.label :mobile_no
      = f.number_field :mobile_no, class: "form-control"
    .col-xs-12.col-lg-4.mb10
      = f.label :fax_no
      = f.number_field :fax_no, class: "form-control"
    .col-xs-12
      | (
      small.field-req  *
      |  )
      i  indicates field is required
  .modal-footer.no-border
    button.btn.btn-default data-dismiss="modal" type="button"  Cancel
    button.btn.btn-primary type="submit" = @branch.new_record? ? "Add Branch" : "Save Changes"

app/views/branches/_show_branch_info.html.slim
.row
  .col-xs-12
    .row.mb10.mt10
      div class="col-xs-#{branch.name.present? ? '4' : '6'}"
        .text-light-grey
          | Branch
        label.text-dark-grey
          span.label.label-primary style="background-color: #{branch.color};" = branch.name
      -if branch.aka.present?  
        .col-xs-4
          .text-light-grey
            | Alias
          label.text-dark-grey
            span.label.label-primary style="background-color: #{branch.color};" = branch.aka    
      div class="col-xs-#{branch.name.present? ? '4' : '6'}"
        .text-light-grey
          | Landline
        label.text-dark-grey = branch.landline_no
    .row.mb10
      .col-xs-4
        .text-light-grey
          | City
        label.text-dark-grey
          = branch.city
      .col-xs-4
        .text-light-grey
          | Fax No.
        label.text-dark-grey = branch.fax_no
      .col-xs-4
        .text-light-grey
          | Delivery Time.
        /label.text-dark-grey = branch.delivery_time? ? branch.delivery_time.to_time.strftime("%l:%M %P") : "--:-- --"
    .row.mb10
      .col-xs-6
        .text-light-grey
          | Address
        label.text-dark-grey
          = branch.address1
      .col-xs-6
        .text-light-grey
          | Mobile No.
        label.text-dark-grey = branch.mobile_no
    .row.mb10
      .col-xs-6
        .text-light-grey
          | Tin Number
        label.text-dark-grey
          = branch.tin_number
      .col-xs-6
        .text-light-grey
          | Company Registered Name
        label.text-dark-grey = branch.company_registered_name
    .row.mb10
      .col-xs-6
        .text-light-grey
          | Zip
        label.text-dark-grey
          = branch.zip
      .col-xs-6
        .text-light-grey
          | E-mail Address
        label.text-dark-grey = branch.email_address
.modal-footer.no-border
  a.btn.btn-default.pull-left data-dismiss="modal" type="button"  Cancel
  - if view_access_control("branches","update")
    = link_to "<i class='icon-glyph f14 mr5'></i> Edit".html_safe, edit_brand_branch_path(branch, brand_id: @brand), class: "btn btn-primary btn-outline", remote: true
  - if view_access_control("branches","destroy")
    = link_to "<i class='icon-glyph-124 f14 mr5'></i> Delete Branch".html_safe, brand_branch_path(id: branch.id, brand_id: @brand.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }

app/views/branches/edit.js.erb
$('#modal h4').html('Edit Branch');

$('.modal-body').html('<%= j render("form") %>');

$('#modal').modal("show");

$('.chosen').chosen({
	width: "100%"
});

$('#init').on('click', function() {
	$('select[name="colorpicker-option-selected"]').simplecolorpicker({theme: 'glyphicons'});
});
$('#init').trigger('click');

app/views/branches/index.html.slim
.panel.panel-primary
	.panel-heading.border.pb45
		.pull-left.mt7 Branches
		.pull-right
			- if view_access_control('branches','create')
				= link_to "<i class='icon-maxicons2-paste mr5'></i> Create Branch".html_safe, '#', data: { toggle: "modal", target: ".create-branch-modal" }, class: "btn btn-default btn-round btn-outline"
	.panel-body
		.no-more-tables
			table.table.table-bordered.table-striped.mb0 data-sortable="true"
				thead
					tr.bg-thead
						th width="425" Name
						th width="425" Address
						th width="150" data-sortable="false" Action
				tbody
					- @branches.each do |branch|
						tr
							td data-title="Name" = branch.name
							td data-title="Address" = branch.address1
							td.action data-title="Action"
								= link_to "<i class='icon-maxicons2-view'></i>".html_safe, '#', class: "btn btn-default btn-xs mb10", data: { tt: "tooltip", placement: "top", "original-title" => "Show Branch", toggle: "modal", target: ".show-branch-#{branch.id}" }
								- if view_access_control('branches','update')
									= link_to "<i class='icon-maxicons2-editting'></i>".html_safe, 'javascript:;', class: "btn btn-default btn-xs mb10", data: { tt: "tooltip", placement: "top", "original-title" => "Edit", toggle: "modal", target: ".edit-branch-#{branch.id}" }
								- if view_access_control('branches','destroy')
									= link_to "<i class='icon-maxicons1-exit'></i>".html_safe, branch_path(branch), method: :delete, class: "btn btn-default btn-xs mb10 swal-warning-confirm", data: { tt: "tooltip", placement: "top", "original-title" => "Delete", confirm: "Are you sure?" }
						.modal class="show-branch-#{branch.id}" tabindex="-1" role="dialog" aria-hidden="true"
							.modal-dialog.modal-sm
								.modal-content
									.modal-header
										button.close type="button" data-dismiss="modal" aria-hidden="true" x
										h4.modal-title = branch.name
									.modal-body
										.row.mb10
											.col-xs-12
												| Address: 
												= branch.address1

						.modal class="edit-branch-#{branch.id}" tabindex="-1" role="dialog" aria-hidden="true"
							.modal-dialog.modal-sm
								.modal-content
									.modal-header
										button.close type="button" data-dismiss="modal" aria-hidden="true" x
										h4.modal-title Edit Branch
									.modal-body
										= form_for branch do |f|
											.row.mb10
												.col-xs-12
													= f.label :name
														| Name 
														small.field-req *
													= f.text_field :name, class: "form-control"
												.col-xs-12
													= f.label :address1, "Address"
													= f.text_field :address1, class: "form-control"
											.row.mb10
												.col-xs-12.mt20
													| ( 
													small.field-req *
													|  ) 
													i indicates field is required
											.modal-footer.no-border
												span.inline.float-right
													= link_to "Cancel", '#', class: "btn btn-default", data: { dismiss: "modal" }
													|  
													= f.submit "Update", class: "btn btn-primary"

.modal.create-branch-modal tabindex="-1" role="dialog" aria-hidden="true"
	.modal-dialog.modal-sm
		.modal-content
			.modal-header
				button.close type="button" data-dismiss="modal" aria-hidden="true" x
				h4.modal-title Create Branch
			.modal-body
				= form_for @branch do |f|
					.row.mb10
						.col-xs-12
							= f.label :name
								| Name 
								small.field-req *
							= f.text_field :name, class: "form-control"
						.col-xs-12
							= f.label :address1, "Address"
							= f.text_field :address1, class: "form-control"
					.row.mb10
						.col-xs-12.mt20
							| ( 
							small.field-req *
							|  ) 
							i indicates field is required
					.modal-footer.no-border
						span.inline.float-right
							= link_to "Cancel", '#', class: "btn btn-default", data: { dismiss: "modal" }
							|  
							= f.submit "Create", class: "btn btn-primary"

app/views/branches/new.js.erb
$('#modal h4').html('Create Branch');

$('.modal-body').html('<%= j render("form") %>');

$('#modal').modal("show");

$('.chosen').chosen({
	width: "100%"
});

$('#init').on('click', function() {
	$('select[name="colorpicker-option-selected"]').simplecolorpicker({theme: 'glyphicons'});
});
$('#init').trigger('click');

app/views/branches/show.js.erb
$('#modal h4').html('<%= @branch.name %>');

$('.modal-body').html('<%= j render("branches/show_branch_info", branch: @branch) %>');

$('#modal').modal("show");