config/routes.rb
  get 'settings' => 'settings#index'
  patch 'update_settings' => 'settings#update_settings'
  patch 'csrab' => 'settings#csrab'
  get 'account/:username' => 'users#account', as: 'account', :constraints => { :username => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ }
  patch 'account/:username/update_account' => 'users#update_account', as: 'update_account'
  patch 'account/:username/change_password' => 'users#change_password', as: 'change_password'
  resource :client, only: [:show, :edit, :update]
  resources :timesheets do
    get :get_branch, on: :collection
    get :get_branch_employees, on: :collection
    get :show_holiday, on: :collection
    get :get_timesheets, on: :collection
    get :export_timesheets, on: :collection
    post "update_timesheets" => "timesheets#update_timesheets"
  end
  resources :employee_benefits
  resources :holidays
  resources :tax_types
  #resources :timesheet_fields
  resources :brands do
    resources :branches
    get :set_purchase_order_restriction, on: :collection
    get :setup_branch_po_setup, on: :collection
    post :create_branch_po_setup, on: :collection
    put :update_branch_po_setup, on: :collection
    get :update_po_schedule, on: :collection
    get :admins_privileges, on: :collection
    post :update_po_privilege, on: :collection
    post :create_purchase_order_setting, on: :collection
    put :update_purchase_order_setting, on: :collection
  end
  resources :roles do
    get 'manage_permissions' => 'permissions#index'
    put 'manage_permissions' => 'permissions#update'
  end
  resources :employees do
    get 'labor_hours' => 'employees#labor_hours'
    get "add_timesheets" => 'employees#add_timesheets'
    put "save_timesheets" => 'employees#save_timesheets'
    get "download_timesheet" => 'employees#download_timesheet'
  end
  resources :labor_hours do
    get 'work_hours_list' => 'labor_hours#work_hours_list'
  end
  resources :settlements
  resources :categories do
    get 'new_subcategory' =>'categories#new_subcategory'
  end
  resources :item_cost_analysis_reports
  resources :shifts, only: [:index,:create,:update,:destroy]
  resources :sales do
    get :confirm, on: :collection
    get "email_form" => "sales#email_form"
    get :sales_setup, on: :collection
    post "send_sale_details" => "sales#send_sale_details"
    post :save_setup, on: :collection
  end
  resources :units
  resources :items
  resources :inventories
  resources :employee_types
  resources :conversions
  resources :suppliers
  resources :manifolds
  resources :directionals
  resources :sale_reports, only: :show
  resources :purchases do
    resources :purchase_items
    get :purchase_order_lookup, on: :collection
    post :purchase_create, on: :collection
    get :purchase_new_record, on: :collection
    post :create_purchase_items, on: :collection
    get "add_purchase_item" => "purchases#add_purchase_item"
    get :edit_purcahse_limit, on: :collection
    post :limit_edit, on: :collection 
    get "view_history_log" => "purchases#view_history_log"
  end
  resources :subscriptions do
    get 'show_branches', on: :collection
    get 'subscribe', on: :collection
  end

  resources :purchase_order_generator, only: [:index, :new] do
    get :get_pos, on: :collection
  end
  resources :bills
  resources :payment_notifications
  post 'paypal_checkout' => 'subscriptions#paypal_checkout'
  get 'process_subscription' => 'subscriptions#process_subscription'
  get 'update_subscription' => 'subscriptions#update_subscription'
  delete 'subscription/:id/cancel', to: 'subscriptions#cancel', as: 'cancel_subscription'
  
  resources :purchase_orders_summary, only: :index 
  resources :purchase_orders_listing, only: :index
  resources :supplier_item_prices
  resources :order_per_suppliers
  resources :order_lists do
    get 'update_status' => 'order_lists#update_status'
  end
  resources :purchase_orders do
    resources :purchase_order_items do
      get :send_email, on: :collection
      get :approve_purchase_order, on: :collection
    end
    get :view_po_remotely, on: :collection
    get :send_bulk_purchase_orders, on: :collection
    get :group_of_purchase_orders, on: :collection
    get :purchase_orders_per_supplier, on: :collection
    get :hold_po, on: :collection
    patch :reject_selected_purchase_orders, on: :collection
    post :mail_bulk_of_purchase_orders, on: :collection
    post 'send_email_notification' => 'purchase_orders#send_email_notification'
    patch 'approve' => 'purchase_orders#approve'
    patch 'hold' => 'purchase_orders#hold'
    patch 'reject' => 'purchase_orders#reject'
    get 'purchase_order' => 'purchase_orders#purchase_order'
    get 'edit_delivery_details' => 'purchase_orders#edit_delivery_details'
    put 'update_delivery_details' => 'purchase_orders#update_delivery_details'
    patch 'save_po_items' => 'purchase_orders#save_po_items'   
  end

  #resources :revenues_setup, as: :revenues
  resources :statistics_setup, as: :statistics
  resources :non_miscellaneous_setup, as: :non_misces
  
  resource :wizard, only: [:show] do
    get 'user_setup' => 'wizards#user_setup'
    get 'company_setup' => 'wizards#company_setup'
    get 'brand_setup' => 'wizards#brand_setup'
    get 'branch_setup' => 'wizards#branch_setup'
    get 'setup_summary' => 'wizards#setup_summary'
    put 'user_setup_complete' => 'wizards#user_setup_complete'
    put 'company_setup_complete' => 'wizards#company_setup_complete'
    put 'brand_setup_complete' => 'wizards#brand_setup_complete'
    put 'branch_setup_complete' => 'wizards#branch_setup_complete'
    put 'setup_summary_complete' => 'wizards#setup_summary_complete'
  end

  get 'directionals/search' => 'directionals#search_entry'

  # ajax
  get 'update_role' => 'pages#update_role'
  get 'update_branch' => 'pages#update_branch'
  get 'update_units' => 'pages#update_units'
  get 'update_price' => 'pages#update_price', as: 'price'
  get 'registration_validate_email' => 'pages#registration_validate_email'
  get 'registration_validate_username' => 'pages#registration_validate_username'
  get 'new_password_validate_email' => 'pages#new_password_validate_email'
  put 'change_brand' => 'pages#change_brand'
  get 'get_plan_info' => 'pages#get_plan_info'
  get 'get_total_amount' => 'pages#get_total_amount'
  get 'get_price' => 'pages#get_price'
  get 'get_units' => 'pages#get_units'
  get 'take_units' => 'pages#take_units'
  get 'validate_time' => "pages#validate_time"
  

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy', as: :logout
    resources :clients do
      get :all_non_subscribers, on: :collection
      get :subscribers, on: :collection
      get :new_clients, on: :collection
      post :subscribe_branches, on: :collection
      get :show_branch_subscriptions, on: :collection
      get "get_total_amount" => "clients#get_total_amount"
      get "get_plan_info" => "clients#get_plan_info"
      post "create_subscription" => "clients#create_subscription"
      post :remove_selected_branches, on: :collection
      post :resubscribe_branches, on: :collection
      get :get_subscription, on: :collection
      post :update_subscription, on: :collection
    end
  end

  namespace :api do
    resources :sales, only: :index do
      get :get_sales_averages, on: :collection
      get :get_customer_count, on: :collection
      get :get_average_revenues, on: :collection
      get :get_sales_per_week, on: :collection
      get :get_sales_per_month, on: :collection
    end

    resources :users, only: :index do
      get :users_per_branch, on: :collection
      get :users_per_brand, on: :collection
    end

    resources :reports, only: :index do
      get :get_invoices, on: :collection
    end

    resources :dashboards, only: :index do
      get :this_week_sales_vs_expense, on: :collection
      get :this_years_sales_expense, on: :collection
      get :monthly_sales_average, on: :collection
      get :monthly_customer_count_average, on: :collection
      get :this_year_total_sales, on: :collection
      get :get_branches_ranking, on: :collection
      get :price_movement, on: :collection
    end

    resources :purchase_order_summary, only: :index do
      get :get_purchase_orders, on: :collection
      get :get_on_hold_pos, on: :collection
      get :get_rejected_pos, on: :collection
    end

    resources :purchase_orders, only: :index do
      get :get_pos, on: :collection
      get :summary, on: :collection
    end

    resources :purchases, only: :index do
      get :searched_purchases, on: :collection
      get :export_excel, on: :collection
      get :default_excel, on: :collection
      get :purchased_items, on: :collection
      get :get_pos_for_purchasing, on: :collection
    end

    resources :item_and_costs, only: :index do
      get :filtered_records, on: :collection
      get :this_month_for_brand_admin, on: :collection
      get :this_week_for_brand_admin, on: :collection
      get :this_month_for_branch_admin, on: :collection
      get :this_week_for_branch_admin, on: :collection
      get :filtered_records_for_brand, on: :collection
      get :filtered_records_for_branch, on: :collection
    end

    resources :items, only: :index

    resources :suppliers, only: [:create, :update]

    resources :activities, only: :index
    
    post "sale_reports" => "sale_reports#create"
    delete 'delete_picture' => 'users#delete_picture', as: :delete_avatar
    
  end
  
  resources :charts, only: [] do
    get :daily_sales, on: :collection
    get :sales_per_branch, on: :collection
    get :get_dates, on: :collection
    get :get_average, on: :collection
    get :get_dashboard_today, on: :collection
    get :customer_count, on: :collection
    get :yearly_sales, on: :collection
    get :today_sales_revenues_expenses, on: :collection
    get :generated_sale_report, on: :collection

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
	before_action :authenticate_user!
	skip_before_action :find_wizard_flag
	before_action :restrict_access

	def show
	end

	def user_setup
	end

	def user_setup_complete
		@user = current_user

		respond_to do |format|
			if params[:user][:first_name].blank?
				@user.errors.add(:first_name, "can't be blank")
			end

			if params[:user][:last_name].blank?
				@user.errors.add(:last_name, "can't be blank")
			end

			if @user.errors.present?
			else
				if @user.update(user_params)
					@user.update(flag: 2)
					ClientUserAccess.find_or_create_by user_id: @user.id
					#format.json { render json: @user.errors.full_messages.join(", "), status: :unprocessable_entity }
				end
			end
			format.js
		end
	end

	def company_setup
	end

	def company_setup_complete
		#current_client.update flag: 2
		#redirect_to brand_setup_wizard_path

		respond_to do |format|
			if client_create_or_update
				format.js
			else
				format.json { render json: @client.errors.full_messages.join(", "), status: :unprocessable_entity }
			end
		end
	end

	def client_create_or_update
		if current_user.client
			@client = current_user.client.update client_params
		else
			@client = Client.create client_params
			if @client.valid?
				current_user.client_user_access.update(client_id: @client.id)
				current_user.update(flag: 3)
			end
		end		
	end

	def brand_setup
	end

	def brand_setup_complete
		#current_client.update flag: 3
		# redirect_to branch_setup_wizard_path

		respond_to do |format|
			if brand_create_or_update
				format.js
			else
				format.json { render json: @brand.errors.full_messages.join(", "), status: :unprocessable_entity }
			end
		end
	end

	def brand_create_or_update
		if current_user.client.brands.present?
			@brand = current_user.client.brands.first.update brand_params
		else
			@brand = current_user.client.brands.create brand_params
			if @brand.valid?
				current_user.update(flag: 4)
			end
		end
	end

	def branch_setup
		
	end

	def branch_setup_complete
		#current_client.update flag: 4
		#redirect_to setup_summary_wizard_path
		
		respond_to do |format|
			# branch_create_or_update
			brand = current_user.client.brands.first
			brand.update(brand_params)
			puts brand_params
			if brand.errors.empty?
				format.js
			else
				format.json { render json: brand.errors.full_messages.join(", "), status: :unprocessable_entity }
			end
		end
	end

	def branch_create_or_update
		brand = current_user.client.brands.first
		@errors = []
		branch_created_count = 0

		if brand.branches.empty?
			params[:branches].each_value do |value|
				if value[:name].present?
					brand.branches.create(name: value[:name], address1: value[:address1])
					branch_created_count += 1
				end
			end
			current_user.update(flag: 5)
		else
			existing_branch = []
			branch = []
			params[:branches].each do |key,value|
				if key.gsub(/([0-9])/, "") == "existing_branch"
					value[:id] = key.gsub("existing_branch","")
					existing_branch << value
				else
					branch << value
				end
			end

			branch.each do |b|
				if b[:name].present?
					brand.branches.create(name: b[:name], address1: b[:address1])
					branch_created_count += 1
				end
			end

			existing_branch.each do |eb|
				b = Branch.find(eb[:id])
				if eb[:name].present?
					b.update(name: eb[:name], address1: eb[:address1])
					branch_created_count += 1
				else
					b.destroy
				end
			end
		end
		@errors << "Please input at least 1 branch" if branch_created_count == 0
		current_user.update(flag: 5) if branch_created_count > 0
	end

	def setup_summary
		
	end

	def setup_summary_complete
		current_user.update(flag: 6)
		current_user.client_user_access.update(role_id: current_user.client.roles.first.id)
		#insert free trial subscription here
		plan = Plan.find 1
		current_client.subscriptions.create(plan_id: 1, status: "Active", start_date: DateTime.now, end_date: (DateTime.now + (plan.duration_in_days).days))
		redirect_to dashboard_path
	end

	private
	def restrict_access
		redirect_to root_path if current_user.flag >= 6
	end

	def user_params
		params.require(:user).permit(:first_name, :last_name)
	end

	def client_params
		params.require(:client).permit(:name, :address1, :contact, :email)
	end

	def brand_params
		params.require(:brand).permit(:name, :website, branches_attributes: [:id, :name, :address1, :_destroy])
	end
end

app/views/wizards/_branch_fields.html.slim
.row.mb10.nested-fields
	.col-xs-10.mb5
		label.control-label Branch
		span.field-req  *
		= f.text_field :name, placeholder: "e.g: Fort Bonifacio", class: "form-control branch_name required"
	.col-xs-2.mb5
		= link_to_remove_association "Remove branch", f
	.col-xs-12.mb5
		label Address
		= f.text_area :address1, placeholder: "Branch Address", class: "form-control", rows:4

app/views/wizards/_branch_setup.html.slim
.content-wrap#branch-setup-form
	.wrapper
		.panel.panel-default
			.panel-body.no-p
				#wizard.wizard
					ul.steps style=("margin-left: 0")
						li
							span.badge.bg-success> ✓
							| Done
						li
							span.badge.bg-success> ✓
							| Done
						li
							span.badge.bg-success> ✓
							| Done
						li.active
							span.badge.bg-primary> 4
							| Branch Setup
						li
							span.badge.bg-primary> 5
							| Step 5
				.step-content
				  #step4.step-pane.active
				  	- @brand = current_user.client.brands.first if current_user.client.brands.present?
				  	= form_for @brand, url: branch_setup_complete_wizard_path, method: :put, remote: true do |f|
				  		#branches
				  			= f.fields_for :branches do |branch|
				  				= render "branch_fields", f: branch
				  			.links.col-xs-12.mb5.text-center
									= link_to_add_association "Add More &amp; Enjoy 60 Days Free trial".html_safe, f, :branches, class: "btn btn-success btn-outline btn-round", id: "add-more-btn"
									p.text-danger#maximum-branch-message style="display:none;" 
										strong Maximum branch count reached
							.row
								.col-xs-12
									.pull-left
										= link_to "Go Back", "#", id: "back-btn", class: "btn btn-default"
									.pull-right
										button.btn.btn-primary type="submit"
											| Next
											i.icon-glyph-99.f14.ml5
						/ - @brand = current_user.client.brands.first if current_user.client.brands.present?
						/ - if @brand.branches.empty? ||  @brand.nil?
						/ 	= form_for :branches, url: branch_setup_complete_wizard_path, method: :put, remote: true, html: { id: "new_branches" } do |f|
						/ 		= f.fields_for :branch1 do |b|
						/ 			= render "branch_field", b: b
						/ 		.col-xs-12.mb5.text-center
						/ 			button.btn.btn-success.btn-outline.btn-round#add-more-btn Add More &amp; Enjoy 60 Days Free trial
						/ 		.row
						/ 			.col-xs-12
						/ 				.pull-left
						/ 					= link_to "Go Back", "#", id: "back-btn", class: "btn btn-default"
						/ 				.pull-right
						/ 					button.btn.btn-primary type="submit"
						/ 						| Next
						/ 						i.icon-glyph-99.f14.ml5
						/ - else
						/ 	- branch_count = @brand.branches.count
						/ 	= form_for :branches, url: branch_setup_complete_wizard_path, method: :put, remote: true, html: { id: "new_branches" } do |f|
						/ 		- branches = @brand.branches.order('id asc')
						/ 		- branches.each_with_index do |branch, index|
						/ 			= f.fields_for "existing_branch#{branch.id}".to_sym, branch do |b|
						/ 				= render "branch_field", b: b
						/ 		- (3 - branch_count).times do |branch|
						/ 			= f.fields_for "branch#{branch + 1}".to_sym do |b|
						/ 				= render "branch_field", b: b
						/ 		.col-xs-12.mb5.text-center
						/ 			button.btn.btn-success.btn-outline.btn-round#add-more-btn Add More &amp; Enjoy 60 Days Free trial
						/ 		.row
						/ 			.col-xs-12
						/ 				.pull-left
						/ 					= link_to "Go Back", "#", id: "back-btn", class: "btn btn-default"
						/ 				.pull-right
						/ 					button.btn.btn-primary type="submit"
						/ 						| Next
						/ 						i.icon-glyph-99.f14.ml5


javascript:
	$(document).ready(function () {
		$('#new_branches').on("ajax:error", function ( e, xhr, status, error) {
			$('p.alert').remove();
			$('#new_branches').prepend("<p class='alert'>" + xhr.responseText + "</p>");
		});
		$('#back-btn').on("click", function (e) {
			e.preventDefault();
			$('.wizard-area').replaceWith("<div class='wizard-area'>#{escape_javascript(render('brand_setup'))}</div>");
		});

		if($('.nested-fields:visible').size() >= 3){
			$('#add-more-btn').hide();
			$('#maximum-branch-message').show();
		}

		if($('.nested-fields:visible').size() == 1){
			$('.remove_fields').hide();
		}

		$('#add-more-btn').on('click',function(e){
			if($('.nested-fields:visible').size() >= 2){
				$('#add-more-btn').hide();
				$('#maximum-branch-message').show();
			}

			if($('.nested-fields:visible').size() == 1){
				$('.remove_fields').show();
			}
		});

		$('body').on('click', '.remove_fields', function(){
			if($('.nested-fields:visible').size() == 3){
				$('#maximum-branch-message').hide();
				$('#add-more-btn').show();
			}
			
			if($('.nested-fields:visible').size() == 2){
				$('.remove_fields').hide();
			}
			else{
				$('.remove_fields').show();
			}
		});

		$('form').submit(function(e){
			var errors = 0;
			$('.required').each(function(){
				if($(this).val().trim() == ""){
					$(this).parent().addClass('has-error');
					errors = errors + 1;
				}
			});
			if(errors > 0){
				return false;
			}
		});
	});

app/views/wizards/_brand_setup.html.slim
.content-wrap#brand-setup-form
	.wrapper
		.panel.panel-default
			.panel-body.no-p
				#wizard.wizard
					ul.steps style=("margin-left: 0")
						li
							span.badge.bg-success> ✓
							| Done
						li
							span.badge.bg-success> ✓
							| Done
						li.active
							span.badge.bg-primary> 3
							| Your Brand
						li
							span.badge.bg-primary> 4
							| Step 4
						li
							span.badge.bg-primary> 5
							| Step 5
				.step-content
				  #step3.step-pane.active
						- if current_user.client.nil?
							- @brand = Brand.new
						- elsif current_user.client.brands.present?
							- @brand = current_user.client.brands.first
						- else
							- @brand = Brand.new
						= form_for @brand, url: brand_setup_complete_wizard_path, method: :put, remote: true do |f|
							.row.mb10
								.col-xs-12.mb5
									label.control-label Brand Name
									span.field-req  *
									= f.text_field :name, placeholder: "Your Restaurant's Name", class: "form-control required"
								.col-xs-12.mb5
									label Website
									.input-group
										span.input-group-addon HTTP://
										= f.text_field :website, placeholder: "Website", class: "form-control"
							.row
								.col-xs-12
									.pull-left
										= link_to "Back", "#", id: "back-btn", class: "btn btn-default"
									.pull-right
										button.btn.btn-primary type="submit"
											| Next
											i.icon-glyph-99.f14.ml5

javascript:
	$(document).ready(function () {
		$('#new_brand').on("ajax:error", function ( e, xhr, status, error) {
			$('p.alert').remove();
			$('#new_brand').prepend("<p class='alert'>" + xhr.responseText + "</p>");
		});
		$('#back-btn').on("click", function (e) {
			e.preventDefault();
			$('.wizard-area').replaceWith("<div class='wizard-area'>#{escape_javascript(render('company_setup'))}</div>");
		});

		$('form').submit(function(e){
			var errors = 0;
			$('.required').each(function(){
				if($(this).val().trim() == ""){
					$(this).parent().addClass('has-error');
					errors = errors + 1;
				}
			});
			if(errors > 0){
				return false;
			}
		});
	});

app/views/wizards/_company_setup.html.slim
.content-wrap#company-setup-form
	.wrapper
		.panel.panel-default
			.panel-body.no-p
				#wizard.wizard
					ul.steps style=("margin-left: 0")
						li
							span.badge.bg-success> ✓
							| Done
						li.active
							span.badge.bg-primary> 2
							| About Your Company
						li
							span.badge.bg-primary> 3
							| Step 3
						li
							span.badge.bg-primary> 4
							| Step 4
						li
							span.badge.bg-primary> 5
							| Step 5
				.step-content
				  #step2.step-pane.active
						- if current_user.client
							- @client = current_user.client
						-	else
							- @client = Client.new
						= form_for @client, url: company_setup_complete_wizard_path, method: :put, remote: true do |f|
							.row.mb10
								.col-xs-12.mb5
									label.control-label Company Name
									span.field-req  *
									= f.text_field :name, placeholder: "e.g: Gousteau Company", class: "form-control required"
								.col-xs-12.mb5
									label Main Address
									= f.text_area :address1, placeholder: "e.g: Paris, France ", class: "form-control", rows:4
								.col-xs-12.mb5
									label Contact No.
									= f.text_field :contact, placeholder: "Landline/Mobile", class: "form-control"
								.col-xs-12.mb5
									label Company Email
									= f.text_field :email, placeholder: "example@company.com", class: "form-control"
							.row
								.col-xs-12
									.pull-left
										= link_to "Back", "#", id: "back-btn", class: "btn btn-default"
									.pull-right
										button.btn.btn-primary type="submit"
											| Next
											i.icon-glyph-99.f14.ml5

javascript:
	$(document).ready(function () {
		$('#new_client').on("ajax:error", function ( e, xhr, status, error) {
			$('p.alert').remove();
			$('#new_client').prepend("<p class='alert'>" + xhr.responseText + "</p>");
		});
		$('#back-btn').on("click", function (e) {
			e.preventDefault();
			$('.wizard-area').replaceWith("<div class='wizard-area'>#{escape_javascript(render('user_setup'))}</div>");
		});

		$('form').submit(function(e){
			var errors = 0;
			$('.required').each(function(){
				if($(this).val().trim() == ""){
					$(this).parent().addClass('has-error');
					errors = errors + 1;
				}
			});
			if(errors > 0){
				return false;
			}
		});
	});

app/views/wizards/_setup_summary.html.slim
.content-wrap#setup-setup-form
	.wrapper
		.panel.panel-default
			.panel-body.no-p
				#wizard.wizard
					ul.steps style=("margin-left: 0")
						li
							span.badge.bg-success> ✓
							| Done
						li
							span.badge.bg-success> ✓
							| Done
						li
							span.badge.bg-success> ✓
							| Done
						li
							span.badge.bg-success> ✓
							| Done
						li.active
							span.badge.bg-primary> 5
							| Finish
				.step-content
				  #step5.step-pane.active
					.row
						.col-xs-12
							p
								.text-light-grey
									| Your name
								label.text-dark-grey = "#{current_user.first_name} #{current_user.last_name}"
							p
								.text-light-grey
									| Company name
								label.text-dark-grey = current_client.name
							p
								.text-light-grey
									| Company address
								label.text-dark-grey = current_client.address1
							p
								.text-light-grey
									| Company contact no.
								label.text-dark-grey = current_client.contact
							p
								.text-light-grey
									| Company email
								label.text-dark-grey = current_client.email
							p
								.text-light-grey
									| Brand name
								label.text-dark-grey = current_client.brands.first.name
							p
								.text-light-grey
									| Brand website
								label.text-dark-grey = current_client.brands.first.website
							- current_client.brands.first.branches.order('id asc').each_with_index do |branch,index|
								p
									.text-light-grey
										= "Branch ##{index + 1} name"
									label.text-dark-grey = branch.name
								p
									.text-light-grey
										= "Branch ##{index + 1} address"
									label.text-dark-grey = branch.address1
					.row
						.col-xs-12
							.pull-left
								= link_to "Back", "#", id: "back-btn", class: "btn btn-default"
							.pull-right
								= link_to "Done", setup_summary_complete_wizard_path, method: :put, class: "btn btn-success"

/ #setup-summary-form
/ 	h2 Setup Summary

/ 	section
/ 		h3 User Info
/ 		p
/ 			| First name:
/ 			| &nbsp;
/ 			= current_user.first_name
/ 		p
/ 			| Last name:
/ 			| &nbsp;
/ 			= current_user.last_name

/ 	section
/ 		h3 Company Info
/ 		p
/ 			| Name:
/ 			| &nbsp;
/ 			= current_user.client.name
/ 		p
/ 			| Address:
/ 			| &nbsp;
/ 			= current_user.client.address1
/ 		p
/ 			| Contact:
/ 			| &nbsp;
/ 			= current_user.client.contact
/ 		p
/ 			| Email:
/ 			| &nbsp;
/ 			= current_user.client.email

/ 	section
/ 		h3 Brand Info
/ 		p
/ 			| Name:
/ 			| &nbsp;
/ 			= current_user.client.brands.first.name
/ 		p
/ 			| Website:
/ 			| &nbsp;
/ 			= current_user.client.brands.first.website

/ 	section
/ 		h3 Branch Info
/ 		- current_user.client.brands.first.branches.order('id asc').each do |branch|
/ 			p
/ 				| Name:
/ 				| &nbsp;
/ 				= branch.name
/ 			p
/ 				| Address:
/ 				| &nbsp;
/ 				= branch.address1

/ 	= link_to "Back", "#", id: "back-btn"
/ 	| &nbsp;
/ 	= link_to "DONE", setup_summary_complete_wizard_path, method: :put

javascript:
	$(document).ready(function (){
		$('#back-btn').on("click", function (e) {
			e.preventDefault();
			$('.wizard-area').replaceWith("<div class='wizard-area'>#{escape_javascript(render('branch_setup'))}</div>");
		});
	});

app/views/wizards/branch_setup_complete.js.erb
$('.wizard-area').replaceWith("<div class='wizard-area'><%= j render('setup_summary') %></div>");

app/views/wizards/brand_setup_complete.js.erb
$('.wizard-area').replaceWith("<div class='wizard-area'><%= j render('branch_setup') %></div>");

app/views/wizards/company_setup_complete.js.erb
$('.wizard-area').replaceWith("<div class='wizard-area'><%= j render('brand_setup') %></div>");

app/views/wizards/user_setup_complete.js.erb
<% if @user.errors.empty? %>
	$('.wizard-area').replaceWith("<div class='wizard-area'><%= j render('company_setup') %></div>");
<% else %>
	// $('.wizard-area').prepend("<p><%= @user.errors.full_messages %></p>");
<% end %>
// $('#user-setup-form').hide();
// $('.wizard-area').append("<%= j render('company_setup') %>");