config/routes.rb
  get 'invoice_entry_report' => 'reports#invoice_entry_report'
  get 'update_item' => 'reports#update_item'
  get 'man_hours' => 'reports#man_hours'
  resources :reports, only: [] do
    get :get_purchased_items_per_item, on: :collection
  end
  get 'profit_and_losses' => 'profit_and_losses#index'
  get 'settings' => 'settings#index'
  patch 'update_settings' => 'settings#update_settings'
  patch 'csrab' => 'settings#csrab'
  get 'account/:username' => 'users#account', as: 'account', :constraints => { :username => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ }
  patch 'account/:username/update_account' => 'users#update_account', as: 'update_account'
  patch 'account/:username/change_password' => 'users#change_password', as: 'change_password'
  resource :client, only: [:show, :edit, :update]
  resources :timesheets do
    get :get_branch, on: :collection
    get :get_branch_employees, on: :collection
    get :show_holiday, on: :collection
    get :get_timesheets, on: :collection
    get :export_timesheets, on: :collection
    post "update_timesheets" => "timesheets#update_timesheets"
  end
  resources :employee_benefits
  resources :holidays
  resources :tax_types
  #resources :timesheet_fields
  resources :brands do
    resources :branches
    get :set_purchase_order_restriction, on: :collection
    get :setup_branch_po_setup, on: :collection
    post :create_branch_po_setup, on: :collection
    put :update_branch_po_setup, on: :collection
    get :update_po_schedule, on: :collection
    get :admins_privileges, on: :collection
    post :update_po_privilege, on: :collection
    post :create_purchase_order_setting, on: :collection
    put :update_purchase_order_setting, on: :collection
  end
  resources :roles do
    get 'manage_permissions' => 'permissions#index'
    put 'manage_permissions' => 'permissions#update'
  end
  resources :employees do
    get 'labor_hours' => 'employees#labor_hours'
    get "add_timesheets" => 'employees#add_timesheets'
    put "save_timesheets" => 'employees#save_timesheets'
    get "download_timesheet" => 'employees#download_timesheet'
  end
  resources :labor_hours do
    get 'work_hours_list' => 'labor_hours#work_hours_list'
  end
  resources :settlements
  resources :categories do
    get 'new_subcategory' =>'categories#new_subcategory'
  end
  resources :item_cost_analysis_reports
  resources :shifts, only: [:index,:create,:update,:destroy]
  resources :sales do
    get :confirm, on: :collection
    get "email_form" => "sales#email_form"
    get :sales_setup, on: :collection
    post "send_sale_details" => "sales#send_sale_details"
    post :save_setup, on: :collection
  end
  resources :units
  resources :items
  resources :inventories
  resources :employee_types
  resources :conversions
  resources :suppliers
  resources :manifolds
  resources :directionals
  resources :sale_reports, only: :show
  resources :purchases do
    resources :purchase_items
    get :purchase_order_lookup, on: :collection
    post :purchase_create, on: :collection
    get :purchase_new_record, on: :collection
    post :create_purchase_items, on: :collection
    get "add_purchase_item" => "purchases#add_purchase_item"
    get :edit_purcahse_limit, on: :collection
    post :limit_edit, on: :collection 
    get "view_history_log" => "purchases#view_history_log"
  end
  resources :subscriptions do
    get 'show_branches', on: :collection
    get 'subscribe', on: :collection
  end

  resources :purchase_order_generator, only: [:index, :new] do
    get :get_pos, on: :collection
  end
  resources :bills
  resources :payment_notifications
  post 'paypal_checkout' => 'subscriptions#paypal_checkout'
  get 'process_subscription' => 'subscriptions#process_subscription'
  get 'update_subscription' => 'subscriptions#update_subscription'
  delete 'subscription/:id/cancel', to: 'subscriptions#cancel', as: 'cancel_subscription'
  
  resources :purchase_orders_summary, only: :index 
  resources :purchase_orders_listing, only: :index
  resources :supplier_item_prices
  resources :order_per_suppliers
  resources :order_lists do
    get 'update_status' => 'order_lists#update_status'
  end
  resources :purchase_orders do
    resources :purchase_order_items do
      get :send_email, on: :collection
      get :approve_purchase_order, on: :collection
    end
    get :view_po_remotely, on: :collection
    get :send_bulk_purchase_orders, on: :collection
    get :group_of_purchase_orders, on: :collection
    get :purchase_orders_per_supplier, on: :collection
    get :hold_po, on: :collection
    patch :reject_selected_purchase_orders, on: :collection
    post :mail_bulk_of_purchase_orders, on: :collection
    post 'send_email_notification' => 'purchase_orders#send_email_notification'
    patch 'approve' => 'purchase_orders#approve'
    patch 'hold' => 'purchase_orders#hold'
    patch 'reject' => 'purchase_orders#reject'
    get 'purchase_order' => 'purchase_orders#purchase_order'
    get 'edit_delivery_details' => 'purchase_orders#edit_delivery_details'
    put 'update_delivery_details' => 'purchase_orders#update_delivery_details'
    patch 'save_po_items' => 'purchase_orders#save_po_items'   
  end

  #resources :revenues_setup, as: :revenues
  resources :statistics_setup, as: :statistics
  resources :non_miscellaneous_setup, as: :non_misces
  
  resource :wizard, only: [:show] do
    get 'user_setup' => 'wizards#user_setup'
    get 'company_setup' => 'wizards#company_setup'
    get 'brand_setup' => 'wizards#brand_setup'
    get 'branch_setup' => 'wizards#branch_setup'
    get 'setup_summary' => 'wizards#setup_summary'
    put 'user_setup_complete' => 'wizards#user_setup_complete'
    put 'company_setup_complete' => 'wizards#company_setup_complete'
    put 'brand_setup_complete' => 'wizards#brand_setup_complete'
    put 'branch_setup_complete' => 'wizards#branch_setup_complete'
    put 'setup_summary_complete' => 'wizards#setup_summary_complete'
  end

  get 'directionals/search' => 'directionals#search_entry'

  # ajax
  get 'update_role' => 'pages#update_role'
  get 'update_branch' => 'pages#update_branch'
  get 'update_units' => 'pages#update_units'
  get 'update_price' => 'pages#update_price', as: 'price'
  get 'registration_validate_email' => 'pages#registration_validate_email'
  get 'registration_validate_username' => 'pages#registration_validate_username'
  get 'new_password_validate_email' => 'pages#new_password_validate_email'
  put 'change_brand' => 'pages#change_brand'
  get 'get_plan_info' => 'pages#get_plan_info'
  get 'get_total_amount' => 'pages#get_total_amount'
  get 'get_price' => 'pages#get_price'
  get 'get_units' => 'pages#get_units'
  get 'take_units' => 'pages#take_units'
  get 'validate_time' => "pages#validate_time"
  

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy', as: :logout
    resources :clients do
      get :all_non_subscribers, on: :collection
      get :subscribers, on: :collection
      get :new_clients, on: :collection
      post :subscribe_branches, on: :collection
      get :show_branch_subscriptions, on: :collection
      get "get_total_amount" => "clients#get_total_amount"
      get "get_plan_info" => "clients#get_plan_info"
      post "create_subscription" => "clients#create_subscription"
      post :remove_selected_branches, on: :collection
      post :resubscribe_branches, on: :collection
      get :get_subscription, on: :collection
      post :update_subscription, on: :collection
    end
  end

  namespace :api do
    resources :sales, only: :index do
      get :get_sales_averages, on: :collection
      get :get_customer_count, on: :collection
      get :get_average_revenues, on: :collection
      get :get_sales_per_week, on: :collection
      get :get_sales_per_month, on: :collection
    end

    resources :users, only: :index do
      get :users_per_branch, on: :collection
      get :users_per_brand, on: :collection
    end

    resources :reports, only: :index do
      get :get_invoices, on: :collection
    end

    resources :dashboards, only: :index do
      get :this_week_sales_vs_expense, on: :collection
      get :this_years_sales_expense, on: :collection
      get :monthly_sales_average, on: :collection
      get :monthly_customer_count_average, on: :collection
      get :this_year_total_sales, on: :collection
      get :get_branches_ranking, on: :collection
      get :price_movement, on: :collection
    end

    resources :purchase_order_summary, only: :index do
      get :get_purchase_orders, on: :collection
      get :get_on_hold_pos, on: :collection
      get :get_rejected_pos, on: :collection
    end

    resources :purchase_orders, only: :index do
      get :get_pos, on: :collection
      get :summary, on: :collection
    end

    resources :purchases, only: :index do
      get :searched_purchases, on: :collection
      get :export_excel, on: :collection
      get :default_excel, on: :collection
      get :purchased_items, on: :collection
      get :get_pos_for_purchasing, on: :collection
    end

    resources :item_and_costs, only: :index do
      get :filtered_records, on: :collection
      get :this_month_for_brand_admin, on: :collection
      get :this_week_for_brand_admin, on: :collection
      get :this_month_for_branch_admin, on: :collection
      get :this_week_for_branch_admin, on: :collection
      get :filtered_records_for_brand, on: :collection
      get :filtered_records_for_branch, on: :collection
    end

    resources :items, only: :index

    resources :suppliers, only: [:create, :update]

    resources :activities, only: :index
    
    post "sale_reports" => "sale_reports#create"
    delete 'delete_picture' => 'users#delete_picture', as: :delete_avatar
    
  end
  
  resources :charts, only: [] do
    get :daily_sales, on: :collection
    get :sales_per_branch, on: :collection
    get :get_dates, on: :collection

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	before_action :authenticate_user!

	def index
		@subscriptions = current_client.subscriptions
		@free_trial = current_client.trial
		@branches_count = current_client.branches.count
		@profile_token = current_branch.name.downcase.gsub(/ /, '-') + "-" + current_branch.aka.downcase + "-" + current_branch.branch_subscription.subscription.paypal_recurring_profile_token if branch_admin?
	end

	def new
		@subscription = current_client.subscription
	end

	def subscribe
		@subscription = current_client.subscriptions.new
		@branches = current_client.branches.pluck :name
		@action = current_client.has_subscribed? ? "update" : "create"
	end

  def cancel
    subscription = Subscription.find(params[:id])

    ppr = PayPal::Recurring.new(:profile_id => subscription.paypal_recurring_profile_token)
    response = ppr.cancel
    if response.success?
      subscription.status = "Cancelled"
      subscription.save
      respond_to do |format|
        format.html { redirect_to subscriptions_path, notice: 'Subscription cancellation in progress..' }
        format.json { head :no_content }
      end
    else
      raise response.errors.inspect
    end
  end

  def show_branches
		@branches = current_client.branches
		@color = if current_client.free_trial?
			current_client.on_free_trial? ? "green" : "red"
		else 
			current_client.has_paid_subscription? ? "green" : "red"
		end
		@label = if current_client.free_trial?
							current_client.on_free_trial? ? "" : "Expired"
						else
							""
						end
  end

	def process_subscription
		if params[:branches] && params[:PayerID] && params[:token]
			branches = params[:branches]
			plan = Plan.find 2
			@subscription = current_client.subscriptions.build
			@subscription.paypal_customer_token = params[:PayerID]
			@subscription.paypal_payment_token = params[:token]	
			@subscription.plan_id = plan.id
			@subscription.branch_count = branches.count
			@subscription.amount = plan.amount * branches.count
			@subscription.period = plan.period	
			if @subscription.request_pay
				if @subscription.save_with_payment
					current_client.unsubscribed_branches.where(id: branches).each do |branch|
						branch.create_branch_subscription(subscription_id: @subscription.id)
					end
					redirect_to subscriptions_path, notice: "Thank you for Subscribing! Your subscription is now being processed through PayPal. This would only take a few moments."
				else
					redirect_to subscriptions_path, alert: @subscription.errors.full_messages.join(", ")
				end
			else 
				redirect_to subscriptions_path, alert: @subscription.errors.full_messages.join(", ")
			end
		end
	end

	def update_subscription
		if params[:branches] && params[:PayerID] && params[:token] && params[:subscription_id]
			branches = params[:branches]
			existing_branch_count = current_client.branches.size
			plan = Plan.find 2
			@subscription = current_client.subscriptions.find params[:subscription_id]
			@subscription.paypal_payment_token = params[:token]
			@subscription.paypal_customer_token = params[:PayerID]
			@subscription.plan_id = plan.id
			@subscription.branch_count = branches.count
			@subscription.amount = plan.amount * ( branches.count + existing_branch_count )
			@subscription.period = plan.period
			if @subscription.update_with_payment
				current_client.unsubscribed_branches.where(id: branches).each do |branch|
					branch.create_branch_subscription(subscription_id: @subscription.id)
				end
				redirect_to subscriptions_path, notice: "You have successfully updated your subscription for additional #{branches.count + existing_branch_count} branch(es). This could only take a few moments."
			else
				redirect_to subscriptions_path, alert: @subscription.errors.full_messages.join(", ")
			end
		end
	end

	def paypal_checkout
		branches = params[:subscription][:branches].select { |b| b.present? }
		#branches = params[:subscription][:branches].select { |b| b.present? }
		if branches.empty?
			redirect_to subscriptions_path, alert: "Subscription creation failed. You dont have branches to pay yet."
		else
			plan = Plan.find 2
			subscription = current_client.subscriptions.build(plan_id: plan.id)
			if params[:subscription][:paypal_action].eql? 'create'
				redirect_to subscription.paypal.checkout_url(
					return_url: process_subscription_url(:plan_id => plan.id, branches: branches),
					cancel_url: subscriptions_url,
					description: "#{plan.name} for a total of #{branches.count} #{'branch'.pluralize(branches.count)}",
					amount: plan.amount * branches.count,
					currency: "PHP"
				)
			else
				branches_count = current_client.branches.size + branches.count
				redirect_to subscription.paypal.checkout_url(
					return_url: update_subscription_url(:plan_id => plan.id, branches: branches),
					cancel_url: subscriptions_url,
					description: "#{plan.name} for a total of #{branches_count} #{'branch'.pluralize(branches_count)}",
					amount: plan.amount * branches_count,
					currency: "PHP"
				)
			end
		 end
	end
end

app/views/subscriptions/_form.html.slim
= form_for @subscription, url: paypal_checkout_path, method: :post do |f|
	.row.mb10#no-branch-selected-error style="display:none;"
		.col-xs-12
			p.bg-danger Please select at least one branch
	.row.mb10
		.col-xs-12
			= f.label :plan_id, "Monthly Subscription of Php #{Plan.find(2).amount.to_i}"
			= f.hidden_field :plan_id, value: 2
			= f.hidden_field :paypal_action, value: @action
	.row.mb10
		.col-xs-12
			.no-more-tables
				table.table.table-bordered.mb0
					thead
						tr
							th style="text-align: center" width="15%"
								span#all_select Select All 
								br
								input#select_all type="checkbox"
							th Branch
					tbody
						- if current_client.unsubscribed_branches.empty?
							tr
								td colspan="2"
									| No branch available. You can create new branches 
									= link_to "here", brand_path(current_brand)
						- else
							= f.collection_check_boxes :branches, current_client.unsubscribed_branches, :id, :name, class: 'checkbox' do |b|
								- if current_client.on_free_trial?
									tr
										= b.label do
											td style="text-align: center" = b.check_box
											td = "#{b.label} (Free Trial: #{distance_of_time_in_words_to_now(current_client.trial.end_date)} left)".html_safe
								- else
									tr
										= b.label do
											td style="text-align: center" = b.check_box
											td = b.label

			/= f.select :branches, current_client.unsubscribed_branches.pluck(:name, :id), { include_blank: true }, class: "chosen", data: { placeholder: "Select branches to include" }, style: "width: 100%; display: none;", multiple: true
	.row.mb10
		.col-xs-12
			hr
				p
					| Rate per branch: Php 
					span#amount-value
					| &nbsp;
					span#period-value
				.no-more-tables
					table.table.table-bordered.mb0
						thead
							tr.bg-thead
								th width="80%" Branch
								th width="20%" style="text-align: right" Amount
						tbody#branches

						tfoot
							- if current_client.has_subscribed?
								tr
									td style="text-align: right"
										b Your Current Monthly Subscription
									td style="text-align: right"
										b = "Php #{current_client.subscribed_branches.size * Plan.find(2).amount}"
								tr
									td style="text-align: right"
										b Added Monthly Subscription for <span id="branch_count">(0 branch)</span>
									td style="text-align: right"
										b#added = "Php 0.00"
							tr
								td style="text-align: right"
									- if current_client.has_subscribed?
										b New Total Monthly Subscription
									- else
										b Total		
								td#total style="text-align: right"
									- if current_client.has_subscribed?
										b = "Php #{current_client.subscribed_branches.size * Plan.find(2).amount}"
									- else
										b Php 0.00
							
			hr
	.modal-footer.no-border
		span.inline.float-right
			= link_to "Cancel", '#', class: "btn btn-default", data: { dismiss: "modal" }
			= f.submit "Subscribe via PayPal", class: "btn btn-primary"

javascript:
	var plan_id = $('#subscription_plan_id').val();
	var get_plan_info_path = "#{get_plan_info_path}?plan_id="+plan_id;
	$.getJSON(get_plan_info_path, function( json ){
		$('#amount-value').html(json.amount);
		$('#period-value').html(json.period);
	});
	
	$("#select_all").on('change', function(){
		if($(this).prop('checked')){
			var amount = 2500;
			var period = "monthly";
			var selected = $('input[type=checkbox]').not("#select_all").length;
			$('#branches').empty();
			$('input:checkbox').not(this).prop('checked', this.checked).each(function(index, value){		
				var id = $(this).prop("id");
				var label = $("label[for="+id+"]");
				$('#branches').append("<tr><td>"+label.text()+"</td><td style='text-align: right'>Php "+amount+"</td><tr>");
			});
			$('#all_select').text("Unselect All")
			$.ajax({
				url: "#{get_total_amount_url}",
				method: 'GET',
				data: {
					branches: selected,
					plan_id: $('#subscription_plan_id').val()
				},
				success: (data) => {
					$('#branch_count').html(data.branch_count);
					$('#added').html("<b>Php "+data.new_amount+"<br>"+period+"</b>");
					$('#total').html("<b>Php "+data.amount+"<br>"+period+"</b>");
				}
			});	
		}else{
			$('#branches').empty();
			$('input:checkbox').not(this).removeAttr('checked');
			$.ajax({
				url: "#{get_total_amount_url}",
				method: 'GET',
				data: {
					branches: 0,
					plan_id: $('#subscription_plan_id').val()
				},
				success: (data) => {
					$('#branch_count').html("(0) branch");
					$('#added').html("<b>Php 0.00 monthly</b>");
					$('#total').html("<b>Php "+data.amount+"<br>"+data.period+"</b>");
				}
			});	
			$('#all_select').text("Select All")
		}
	});

	$('#subscription_plan_id').on('change', function(){
		var plan_id = $('#subscription_plan_id').val();
		var get_plan_info_path = "#{get_plan_info_path}?plan_id="+plan_id;
		$.getJSON(get_plan_info_path, function( json ){
			$('#amount-value').html(json.amount);
			$('#period-value').html(json.period);
			var selected = $('input:checked');
			var amount = 2500;
			var period = "monthly";
			$('#branches').empty();
			$.each(selected, function( index, value ){
				var id = $(this).prop("id");
				var label = $("label[for="+id+"]");
				$('#branches').append("<tr><td>"+label.text()+"</td><td style='text-align: right'>Php "+amount+"</td><tr>");
			});
		});
	});
	$('input[type=checkbox]').not("#select_all").on('change', function(){
		var selected = $('input:checked').not("#select_all");
		var amount = $('#amount-value').text();
		var period = $('#period-value').text();
		$('#branches').empty();
		$.each(selected, function( index, value ){
			var id = $(this).prop("id");
			var label = $("label[for="+id+"]");
			$('#branches').append("<tr><td>"+label.text()+"</td><td style='text-align: right'>Php "+amount+"</td><tr>");
		});
		$.ajax({
			url: "#{get_total_amount_url}",
			method: 'GET',
			data: {
				branches: selected.length,
				plan_id: $('#subscription_plan_id').val()
			},
			success: (data) => {
				$('#branch_count').html(data.branch_count);
				$('#added').html("<b>Php "+data.new_amount+"<br>"+period+"</b>");
				$('#total').html("<b>Php "+data.amount+"<br>"+data.period+"</b>");
				//$('#total').html("<b>Php "+data.amount+"<br>"+data.period+"</b>");
			}
		});	
	});
	$('form').submit(function(e){
		$('#no-branch-selected-error').hide();
		var selected = $('input:checked');
		if(selected.length > 0){
			$('.modal-content').addClass("panel-refreshing");
		}
		else{
			e.preventDefault();
			$('#no-branch-selected-error').show();
		}
	});

app/views/subscriptions/_show_branches.html.slim
.panel
	- @branches.pluck(:name).each do |b|
		.row.mb15.ml15
			.col-xs-6
				p = b
			.col-xs-6
				p = "#{ current_client.on_free_trial? ? 'Php 0.00 / month' : 'Php 2500 / month'}"

	.row.mt15
		.col-xs-6
			p <b> Total: </b>
		.col-xs-6
			p
				b = "Php #{ current_client.on_free_trial? ? '0.00' : @branches.count * 2500 } monthly subscription"

app/views/subscriptions/index.html.slim
- content_for :title, 'Restobot | Subscriptions'
.panel
	.panel-heading.border.pb45
		.pull-left.mt7 Your Current Subscription

		.pull-right
			- if view_access_control('subscriptions','create')
				= link_to "<i class='icon-glyph-164 f14 mr5'></i> Subscribe".html_safe, subscribe_subscriptions_path, class: "btn btn-success btn-round btn-outline", remote: true
	.panel-body
		- if current_client.free_trial_expired?
			.alert.alert-danger role="alert"
				.row
					.hidden-xs.col-sm-1.text-right
						i.icon-glyph-93.f35
					.col-xs-11.mt5
						- if branch_admin?
							| Your free trial for this branch has already expired. Please contact your admin for your subscription to continue using restobot.
						- else
							| Your Free Trial has already Expired. To continue using Restobot, please subscribe now.
						/- if subtitle
						/	br = subtitle.html_safe
		- elsif current_client.has_paid_subscription?
			.row.mb10
				- if branch_admin?
					- subs = current_branch.branch_subscription.subscription
					.col-lg-offset-2.col-lg-8.col-md-offset-1.col-md-10.col-xs-12 style='padding: 10px' 
						.row.p10.mb10 style='border: 1px solid #D3D3D3; margin: 10px'	
							h4 
								= @profile_token
							h6
								span class="#{subs.payment_provided? && subs.has_paid_on_time? ? 'green' : 'red'}"
									= "#{subs.start_date.strftime('%B %d, %Y')} - #{subs.end_date.strftime('%B %d, %Y')}"	
							.col-xs-12
								p style='font-size: 13px' = "#{subs.plan.name} subscription of #{to_peso subs.plan.amount}".html_safe
				- else
					- current_client.subscriptions.where(plan_id: 2).map do |subs|
						.col-lg-offset-2.col-lg-8.col-md-offset-1.col-md-10.col-xs-12 style='padding: 10px' 
							.row.p10.mb10 style='border: 1px solid #D3D3D3; margin: 10px'	
								h4 
									= subs.paypal_recurring_profile_token
								h6
									span class="#{subs.payment_provided? && subs.has_paid_on_time? ? 'green' : 'red'}"
										= "#{subs.start_date.strftime('%B %d, %Y')} - #{subs.end_date.strftime('%B %d, %Y')}"	
								.col-xs-12
									p style='font-size: 13px' = "#{subs.plan.name} subscription of <b>#{pluralize(subs.branch_count, 'branch')}</b> with a total amount of ₱ #{subs.amount}".html_safe
		
		- elsif current_client.on_free_trial? #&& !current_client.has_paid_subscription?
			.row.mb10
				.col-xs-offset-1.col-xs-10
					table.table.table-bordered.table-striped.mb0
						thead
							tr
								th Free trial of #{distance_of_time_in_words(@free_trial.end_date, @free_trial.start_date)}
								td From #{@free_trial.start_date.strftime("%B %d, %Y")} - #{@free_trial.end_date.strftime("%B %d, %Y")}
							tr
								th Status
								td 
									span.green #{@free_trial.status} 

							tr
								th Branches
								td 
									= link_to @branches_count, show_branches_subscriptions_path, class: "view-link", data: { tt: "tooltip", placement: "top", "original-title" => "More Info" }, remote: true

							tr
								th Days Remaining
								td
									- if current_client.free_trial?
										span class="#{current_client.on_free_trial? ? 'green' : 'red'}" = distance_of_time_in_words_to_now(@free_trial.end_date)
									- elsif current_client.has_paid_subscription?
										span class="#{current_client.has_paid_subscription? ? 'green' : 'red'}" = distance_of_time_in_words_to_now(@free_trial.end_date)
			

		/.no-more-tables
		/	table.table.table-bordered.table-striped.mb0 data-sortable="true"
		/		thead
		/			tr.bg-thead
		/				th width="200" Plan
		/				th width="110" Branch count
		/				th width="180" Previous payment
		/				th width="180" Next payment
		/				th width="120" Amount
		/				th width="120" data-sortable="false" Status
		/				th.action width="90" data-sortable="false" Action
		/		tbody
		/			- if @subscriptions.empty?
		/				tr
		/					td colspan="100%" style="text-align: center"
		/						em No subscriptions found
		/			- @subscriptions.each do |subscription|
		/					tr
		/						td data-title="Plan" = subscription.plan.name
		/						td data-title="Branch count"
		/							= link_to subscription.branches.count, subscription_show_branches_path(subscription), class: "view-link", data: { tt: "tooltip", placement: "top", "original-title" => "More Info" }, remote: true
		/						td data-title="Previous payment" = to_default_date_format(subscription.previous_payment)
		/						td data-title="Next payment" = to_default_date_format(subscription.next_payment)
		/						td data-title="Amount" = to_dollar subscription.amount.to_f
		/						/ td data-title="Period" = subscription.period
		/						td data-title="Status" = subscription.status
		/						td data-title="Action"
		/							- unless subscription.is_processing?
		/								- unless subscription.cancelled?
		/									= link_to "Cancel", cancel_subscription_path(subscription), method: :delete, class: "btn btn-xs btn-danger", data: { confirm: "Are you sure want to cancel?" }
/
= render "partials/modal"

app/views/subscriptions/new.js.erb
$('#modal h4').html('New Subscription');

$('.modal-body').html('<%= j render("form") %>');

$('.chosen').chosen({
	width: "100%"
})

$('#modal').modal({backdrop: 'static', keyboard: false});
$('#modal').modal("show");

app/views/subscriptions/show_branches.js.erb
$('#modal h4').html("Branch list | <span class='<%= @color %>'><%= free_trial_subscription.plan.name %> <%= @label %></span>");

$('.modal-body').html('<%= j render("show_branches") %>');

$('#modal').modal("show");

app/views/subscriptions/subscribe.js.erb
$('#modal h4').html('SUBSCRIBE VIA PAYPAL');

$('.modal-body').html('<%= j render("form") %>');

$('.chosen').chosen({
	width: "100%"
})

$('#modal').modal({backdrop: 'static', keyboard: false});
$('#modal').modal("show");