config/routes.rb
Rails.application.routes.draw do

  get 'item_cost_analysis_reports/index'

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords" }
  resources :company_users, controller: "users"
  root 'pages#index'
  get 'dashboard' => 'dashboard#index'
  get 'purchase_listings' => 'reports#purchase_listings'
  get 'purchase_summary' => 'reports#purchase_summary'
  get 'item_purchase_detail' => 'reports#item_purchase_detail'
  get 'price_movement_report' => 'reports#price_movement_report'
  get 'invoice_entry_report' => 'reports#invoice_entry_report'
  get 'update_item' => 'reports#update_item'
  get 'man_hours' => 'reports#man_hours'
  resources :reports, only: [] do
    get :get_purchased_items_per_item, on: :collection
  end
  get 'profit_and_losses' => 'profit_and_losses#index'
  get 'settings' => 'settings#index'
  patch 'update_settings' => 'settings#update_settings'
  patch 'csrab' => 'settings#csrab'
  get 'account/:username' => 'users#account', as: 'account', :constraints => { :username => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ }
  patch 'account/:username/update_account' => 'users#update_account', as: 'update_account'
  patch 'account/:username/change_password' => 'users#change_password', as: 'change_password'
  resource :client, only: [:show, :edit, :update]
  resources :timesheets do
    get :get_branch, on: :collection
    get :get_branch_employees, on: :collection
    get :show_holiday, on: :collection
    get :get_timesheets, on: :collection
    get :export_timesheets, on: :collection
    post "update_timesheets" => "timesheets#update_timesheets"
  end
  resources :employee_benefits
  resources :holidays
  resources :tax_types
  #resources :timesheet_fields
  resources :brands do
    resources :branches
    get :set_purchase_order_restriction, on: :collection
    get :setup_branch_po_setup, on: :collection
    post :create_branch_po_setup, on: :collection
    put :update_branch_po_setup, on: :collection
    get :update_po_schedule, on: :collection
    get :admins_privileges, on: :collection
    post :update_po_privilege, on: :collection
    post :create_purchase_order_setting, on: :collection
    put :update_purchase_order_setting, on: :collection
  end
  resources :roles do
    get 'manage_permissions' => 'permissions#index'
    put 'manage_permissions' => 'permissions#update'
  end
  resources :employees do
    get 'labor_hours' => 'employees#labor_hours'
    get "add_timesheets" => 'employees#add_timesheets'
    put "save_timesheets" => 'employees#save_timesheets'
    get "download_timesheet" => 'employees#download_timesheet'
  end
  resources :labor_hours do
    get 'work_hours_list' => 'labor_hours#work_hours_list'
  end
  resources :settlements
  resources :categories do
    get 'new_subcategory' =>'categories#new_subcategory'
  end
  resources :item_cost_analysis_reports
  resources :shifts, only: [:index,:create,:update,:destroy]
  resources :sales do
    get :confirm, on: :collection
    get "email_form" => "sales#email_form"
    get :sales_setup, on: :collection
    post "send_sale_details" => "sales#send_sale_details"
    post :save_setup, on: :collection
  end
  resources :units
  resources :items
  resources :inventories
  resources :employee_types
  resources :conversions
  resources :suppliers
  resources :manifolds
  resources :directionals
  resources :sale_reports, only: :show
  resources :purchases do
    resources :purchase_items
    get :purchase_order_lookup, on: :collection
    post :purchase_create, on: :collection
    get :purchase_new_record, on: :collection
    post :create_purchase_items, on: :collection
    get "add_purchase_item" => "purchases#add_purchase_item"
    get :edit_purcahse_limit, on: :collection
    post :limit_edit, on: :collection 
    get "view_history_log" => "purchases#view_history_log"
  end
  resources :subscriptions do
    get 'show_branches', on: :collection
    get 'subscribe', on: :collection
  end

  resources :purchase_order_generator, only: [:index, :new] do
    get :get_pos, on: :collection
  end
  resources :bills
  resources :payment_notifications
  post 'paypal_checkout' => 'subscriptions#paypal_checkout'
  get 'process_subscription' => 'subscriptions#process_subscription'
  get 'update_subscription' => 'subscriptions#update_subscription'
  delete 'subscription/:id/cancel', to: 'subscriptions#cancel', as: 'cancel_subscription'
  
  resources :purchase_orders_summary, only: :index 
  resources :purchase_orders_listing, only: :index
  resources :supplier_item_prices
  resources :order_per_suppliers
  resources :order_lists do
    get 'update_status' => 'order_lists#update_status'
  end
  resources :purchase_orders do
    resources :purchase_order_items do
      get :send_email, on: :collection
      get :approve_purchase_order, on: :collection
    end
    get :view_po_remotely, on: :collection
    get :send_bulk_purchase_orders, on: :collection
    get :group_of_purchase_orders, on: :collection
    get :purchase_orders_per_supplier, on: :collection
    get :hold_po, on: :collection
    patch :reject_selected_purchase_orders, on: :collection
    post :mail_bulk_of_purchase_orders, on: :collection
    post 'send_email_notification' => 'purchase_orders#send_email_notification'
    patch 'approve' => 'purchase_orders#approve'
    patch 'hold' => 'purchase_orders#hold'
    patch 'reject' => 'purchase_orders#reject'
    get 'purchase_order' => 'purchase_orders#purchase_order'
    get 'edit_delivery_details' => 'purchase_orders#edit_delivery_details'
    put 'update_delivery_details' => 'purchase_orders#update_delivery_details'
    patch 'save_po_items' => 'purchase_orders#save_po_items'   
  end

  #resources :revenues_setup, as: :revenues
  resources :statistics_setup, as: :statistics
  resources :non_miscellaneous_setup, as: :non_misces
  
  resource :wizard, only: [:show] do
    get 'user_setup' => 'wizards#user_setup'
    get 'company_setup' => 'wizards#company_setup'
    get 'brand_setup' => 'wizards#brand_setup'
    get 'branch_setup' => 'wizards#branch_setup'
    get 'setup_summary' => 'wizards#setup_summary'
    put 'user_setup_complete' => 'wizards#user_setup_complete'
    put 'company_setup_complete' => 'wizards#company_setup_complete'
    put 'brand_setup_complete' => 'wizards#brand_setup_complete'
    put 'branch_setup_complete' => 'wizards#branch_setup_complete'
    put 'setup_summary_complete' => 'wizards#setup_summary_complete'
  end

  get 'directionals/search' => 'directionals#search_entry'

  # ajax
  get 'update_role' => 'pages#update_role'
  get 'update_branch' => 'pages#update_branch'
  get 'update_units' => 'pages#update_units'
  get 'update_price' => 'pages#update_price', as: 'price'
  get 'registration_validate_email' => 'pages#registration_validate_email'
  get 'registration_validate_username' => 'pages#registration_validate_username'
  get 'new_password_validate_email' => 'pages#new_password_validate_email'
  put 'change_brand' => 'pages#change_brand'
  get 'get_plan_info' => 'pages#get_plan_info'
  get 'get_total_amount' => 'pages#get_total_amount'
  get 'get_price' => 'pages#get_price'
  get 'get_units' => 'pages#get_units'
  get 'take_units' => 'pages#take_units'
  get 'validate_time' => "pages#validate_time"
  

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy', as: :logout
    resources :clients do
      get :all_non_subscribers, on: :collection
      get :subscribers, on: :collection
      get :new_clients, on: :collection
      post :subscribe_branches, on: :collection
      get :show_branch_subscriptions, on: :collection
      get "get_total_amount" => "clients#get_total_amount"
      get "get_plan_info" => "clients#get_plan_info"
      post "create_subscription" => "clients#create_subscription"
      post :remove_selected_branches, on: :collection
      post :resubscribe_branches, on: :collection
      get :get_subscription, on: :collection
      post :update_subscription, on: :collection
    end
  end

  namespace :api do
    resources :sales, only: :index do
      get :get_sales_averages, on: :collection
      get :get_customer_count, on: :collection
      get :get_average_revenues, on: :collection
      get :get_sales_per_week, on: :collection
      get :get_sales_per_month, on: :collection
    end

    resources :users, only: :index do
      get :users_per_branch, on: :collection
      get :users_per_brand, on: :collection
    end

    resources :reports, only: :index do
      get :get_invoices, on: :collection
    end

    resources :dashboards, only: :index do
      get :this_week_sales_vs_expense, on: :collection
      get :this_years_sales_expense, on: :collection
      get :monthly_sales_average, on: :collection
      get :monthly_customer_count_average, on: :collection
      get :this_year_total_sales, on: :collection
      get :get_branches_ranking, on: :collection
      get :price_movement, on: :collection
    end

    resources :purchase_order_summary, only: :index do
      get :get_purchase_orders, on: :collection
      get :get_on_hold_pos, on: :collection
      get :get_rejected_pos, on: :collection
    end

    resources :purchase_orders, only: :index do
      get :get_pos, on: :collection
      get :summary, on: :collection
    end

    resources :purchases, only: :index do
      get :searched_purchases, on: :collection
      get :export_excel, on: :collection
      get :default_excel, on: :collection
      get :purchased_items, on: :collection
      get :get_pos_for_purchasing, on: :collection
    end

    resources :item_and_costs, only: :index do
      get :filtered_records, on: :collection
      get :this_month_for_brand_admin, on: :collection
      get :this_week_for_brand_admin, on: :collection
      get :this_month_for_branch_admin, on: :collection
      get :this_week_for_branch_admin, on: :collection

app/controllers/api/reports_controller.rb
class Api::ReportsController < ApplicationController
    before_action :authenticate_user!

    def index
        @items = current_brand.items.for_inventory.includes(:purchase_items).all
        @user = branch_admin? ? current_user.branch : current_brand
        @date = params[:date].present? ? Date.strptime(params[:date], "%m/%d/%Y") : Date.today
    end

    def get_invoices
        @suppliers = current_brand.suppliers
        @branches = current_branches
        @user = branch_admin? ? current_branch : current_brand
        q = params[:invoice]
        @purchases = if q.present? && ( q[:branch].present? || q[:supplier].present? )
            if q[:date_range].present?
                from = Date.strptime(q[:date_range].split(" - ")[0], "%m/%d/%Y")
                to = Date.strptime(q[:date_range].split(" - ")[1], "%m/%d/%Y")
                @user.purchases.includes(:branch, :supplier).search_purchases(q[:supplier], q[:branch], [], "").where( purchase_date: from..to ).paginate(page: params[:page], per_page: 15)
            else
                @user.purchases.includes(:branch, :supplier).search_purchases(q[:supplier], q[:branch], [], "").paginate(page: params[:page], per_page: 15)
            end
        else
            @user.purchases.includes(:branch, :supplier).where(purchase_date: Date.today.all_week).paginate(page: params[:page], per_page: 15)
        end
    end

end

app/helpers/reports_helper.rb
module ReportsHelper

	def get_price_movement(purchased_items)
		past_price = Array.new
		current_price = purchased_items
		price_movement_values = Array.new
		hash = Hash.new
			
		current_price.each_with_index do |a, index|
			if past_price.empty?
				past_price.append(0)
			else
				past_price.append(current_price[index-1])
			end

			if past_price[index] != 0
				a = current_price[index]
				price_movement_value = past_price[index].purchase_item_amount - current_price[index].purchase_item_amount
				hash = { :branch_name => a.purchase.branch.name, :item => a.item.name, :prev_amount => past_price[index].purchase_item_amount.to_i, :present_amount => a.purchase_item_amount.to_i, :price_movement => price_movement_value }
      end
      price_movement_values.append(hash)
		end
		
		return price_movement_values
	end

	def get_purchased_items(item_id, date_range)
		@purchase_ids = Purchase.select(:id).where(purchase_date: date_range, brand_id: current_brand)
		@purchase_items = PurchaseItem.where(purchase_id: @purchase_ids, item_id: item_id).order('purchase_item_amount ASC')
		
		return @purchase_items
	end

	def get_price_movement_items(item_ids, date_range)
		price_movement = Array.new
		item_ids.each do |item_id|
			purchased_items = get_purchased_items(item_id, date_range)
			price_movement = price_movement + get_price_movement(purchased_items)
		end
		price_movement = price_movement.sort_by{ |a| a[:price_movement].to_i}

		return price_movement
	end
end

app/views/reports/_big_modal.html.slim
.modal#modal aria-hidden="true" role="dialog" tabindex="-1"
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"
					i.icon-glyph-27
        h4.modal-title
      .modal-body

app/views/reports/_branch_date_search.html.slim
- branches = current_client.on_free_trial? ? current_brand.branches : current_brand.subscribed_branches
.row
	.col-xs-12.col-lg-6
		label Branch
		= select_tag :branch_id,  options_from_collection_for_select(branches, "id", "name", params[:branch_id]), class: 'form-control'
	.col-xs-12.col-lg-6
		label Date
		= text_field_tag :date_entry, params[:date_entry], class: 'form-control',  placeholder: "mm/dd/yyyy", data: { provide: "datepicker" }
.row.mt10
	.col-xs-12
		.pull-right
			button.btn.btn-primary data-tt="tooltip" data-placement="top" data-original-title="Search"
				| Search

app/views/reports/_purchases.html.slim
- if purchases.empty?
    tr
        td colspan="9"
            p.text-center.mt5
                i.icon-maxicons3-danger.mr5.text-orange
                | No Records Found
- purchases.each do |purchase|
    tr
        td data-title="Invoice No." = purchase.invoice_number
        td.text-centered data-title="Invoice Date"  = to_default_date_format(purchase.purchase_date)
        td.text-centered data-title="Branch"  = purchase.branch.name
        td.text-centered data-title="Supplier"  = purchase.supplier.name
        td.align-right data-title="Vat Amount" = to_peso(purchase.overall_vat)
        td.align-right data-title="Total Amount" = to_peso(purchase.overall_amount)
        td.align-right data-title="Net Amount"  = to_peso(purchase.overall_net)
        td.text-centered data-title="Entry Date" = purchase.created_at.strftime("%b %d, %Y | %l:%M %P")
        td.text-centered data-title="Created By" = purchase.created_by.full_name

app/views/reports/invoice_entry_report.html.slim
- content_for :title, "Restobot | Invoice Entry Report"
- branches = current_client.on_free_trial? ? current_brand.branches : current_brand.subscribed_branches


= react_component "InvoiceEntryReport", { branchAdmin: branch_admin? }

= render "partials/modal"
/.panel
/	.panel-body
/		= form_for :invoice, url: invoice_entry_report_path, method: 'get', remote: true do |f|
/			.row
/				.col-xs-12.col-lg-4
/					label Branch
/					= f.select :supplier, branches.pluck(:name, :id), { include_blank: "Select Branch" }, class: "form-control", data: { placeholder: "Select Branch" }	
/				.col-xs-12.col-lg-4
/					label Suppliers
/					= f.select :supplier, @suppliers.pluck(:name, :id), { include_blank: "Select Supplier" }, class: "form-control", data: { placeholder: "Select Supplier" }	
/
/				.col-xs-12.col-lg-4
/					label Date
/					= f.text_field :date_range, class: 'form-control drp',  placeholder: "mm/dd/yyyy"
/			.row.mt10
/				.col-xs-12
/					.pull-right
/						= f.submit "Search", class: "btn btn-primary", id: "search-btn", data: { tt: "tooltip", placement: "top", "original-title" => "Search", "loading-text" => "Searching..." }
						
/.panel
/	.panel-heading.border.pb45
/		.pull-left.mt7 Invoice Entry Report
/	.panel-body
/		- if current_brand.purchases.empty?
/			.alert.alert-info role="alert"
/				.row
/					.col-xs-1.text-right
/						i.icon-glyph-73.f25
/					.col-xs-11
/						| Oops! There seems to be no records here. To receive your invoice entry reports:<br>Go to&nbsp;
/						b Data Entry > Purchases > Create Purchase
/		- else
/			.no-more-tables
/				table.table.table-bordered.mb0
/					thead
/						tr.bg-thead
/							th.text-center width="120" Invoice No.
/							th.text-center width="130" Invoice Date
/							th.text-center Branch
/							th.text-center Supplier
/							th.text-center Vat Amount
/							th.text-center Total Amount
/							th.text-center Net Amount
/							th.text-center Entry Date
/							th.text-center Created By
/					tbody#purchases
/						= render partial: "purchases", locals: { purchases: @purchases }
/
/javascript:
/	$('#search-btn').on('click', function () {
 /   var $btn = $(this).button('loading')
  /  // business logic...
    $btn.button('reset')
/ })

app/views/reports/item_cost_analysis_report.slim
- branches = current_client.on_free_trial? ? current_brand.branches : current_brand.subscribed_branches
.panel
	.panel-body
		= form_for item_cost_analysis_report_path, method: 'get' do |f|
			.row
				.col-xs-12.col-lg-6
					label Branch
					= select_tag :branch_id,  options_from_collection_for_select(branches, "id", "name", params[:branch_id]), class: 'form-control', readonly: true, autocomplete: :off
				.col-xs-12.col-lg-6
					label Date
					= text_field_tag :date_entry, params[:date_entry], class: 'form-control',  placeholder: "mm/dd/yyyy", data: { provide: "datepicker" }, readonly: true, autocomplete: :off
			.row.mt10
				.col-xs-12
					.pull-right
						button.btn.btn-primary data-tt="tooltip" data-placement="top" data-original-title="Search"
							| Search
.panel
	.panel-heading.border.pb45
		.pull-left.mt7 Item Cost Analysis Report
	.panel-body
		.no-more-tables
			table.table.table-bordered.table-striped.mb0
				thead
					tr.big-thead
						th colspan="2" = (Date.today).strftime("%B")
						th.ica-primary-thead colspan="3" Beginning Inventory
						th.ica-primary-thead colspan="4" Total Purchases
						th.ica-primary-thead colspan="3" Ending Inventory
						th.ica-primary-thead colspan="4" 	Cost of Goods Sold
					tr.big-thead
						th Name
						th Unit
						th Qty
						th Cost
						th Amount
						th Qty
						th Cost
						th Amount
						th %
						th Qty
						th Cost
						th Amount
						th Qty
						th Cost
						th Amount
						th %
				tbody
					td
					td
					td
					td

app/views/reports/item_purchase_detail.html.slim
- content_for :title, "Restobot | Purchased Items Details"
- branches = current_client.on_free_trial? ? current_brand.branches : current_brand.subscribed_branches
.collapse#show-search class="#{ 'in' if params[:q].present? }"
	.panel
		.panel-body
			= search_form_for @q, url: item_purchase_detail_path do |f|
				.row
					.col-xs-6.col-xs-3
						= f.label :item_id_in, "Item"
						= f.select :item_id_in, current_brand.items.pluck(:name, :id), {}, class: "chosen", placeholder: "Search", multiple: true
					.col-xs-6.col-xs-3
						= f.label :purchase_purchase_date_cont, "Purchase Date"
						- if params[:q][:purchase_purchase_date_gteq].present? && params[:q][:purchase_purchase_date_lteq].present?
							= f.text_field :purchase_purchase_date_cont, class: "form-control drp", placeholder: "Search", value: "#{to_datepicker_format(params[:q][:purchase_purchase_date_gteq])} - #{to_datepicker_format(params[:q][:purchase_purchase_date_lteq])}"
						- else
							= f.text_field :purchase_purchase_date_cont, class: "form-control drp", placeholder: "Search"
					.col-xs-6.col-xs-3
						= f.label :purchase_branch_id_in, "Branch"
						= f.select :purchase_branch_id_in, branches.pluck(:name,:id), {}, class: "chosen", data: { placeholder: "Search" }, style: "width: 100%; display: none;", multiple: true
					.col-xs-6.col-xs-3
						= f.label :purchase_supplier_id_in, "Supplier"
						= f.select :purchase_supplier_id_in, @suppliers, {}, class: "chosen", data: { placeholder: "Search" }, style: "width: 100%; display: none;", multiple: true
				.row.mt10
					.col-xs-12
						.pull-right
							button.btn.btn-primary data-tt="tooltip" data-placement="top" data-original-title="Search"
								| Search

.panel
	.panel-heading.border.pb45
		.pull-left.mt7 Item Purchase Detail
		.pull-right
			- if view_access_control('purchases','create')
				= link_to "<i class='icon-glyph-162 f14 mr5'></i> Download as Excel".html_safe, item_purchase_detail_path(format: :xlsx, q: request.params[:q]), class: "btn btn-success btn-round btn-outline mr10", target: "_blank"
				|
				= link_to "<i class='icon-glyph-162 f14 mr5'></i> Download as PDF".html_safe, item_purchase_detail_path(format: :pdf, q: request.params[:q]), class: "btn btn-success btn-round btn-outline", target: "_blank"
	.panel-body
		- if current_brand.purchases.empty?
			.alert.alert-info role="alert"
				.row
					.col-xs-1.text-right
						i.icon-glyph-73.f25
					.col-xs-11
						| Oops! There seems to be no records of purchase here.<br> Go to&nbsp;
						b Data Entry > Purchases > Create Purchase
		- else
			.no-more-tables
				table.table.table-bordered.table-striped.mb0
					thead
						tr.bg-thead
							th Branch
							th Invoice Date
							th Supplier
							th Item name
							th Quantity
							th Unit Amount
							th Total Amount
					tbody
						- @purchase_items = @purchases.group_by{|t| t.purchase_id }
						- if @purchase_items.empty?
							td.text-center colspan="7"
								| No records found from &nbsp;
								i
									b
										= "#{to_datepicker_format(params[:q][:purchase_purchase_date_gteq])} - #{to_datepicker_format(params[:q][:purchase_purchase_date_lteq])}"
						- @purchase_items.each do |test, purchase_items|
						  - @total_unit_amount = 0
						  - @total_quantity = 0

						  - purchase_items.each do |listing|
						    - vcs = vat_computation_summary([listing])
						    /-# For Each @purchases Generate one of each Invoice Amount, Net Amount, Purchase Amount
						    /-# vcs = vat_computation_summary(purchase) %> <%# computations for VAT %>
						    - @quantity = number_with_precision(listing.quantity, precision: 2)
						    - @net_amount = vcs[0]
						    - @nonideal_amount = vcs[2]
						    - @total_purchase_amount = vcs[2]
						    - @vat_amount = vcs[1]
						    - if listing.vat_type == "VAT-Exclusive"
						      - @unit_price = @net_amount.to_f / @quantity.to_f
						    - else
						      - @total_purchase_amount = vcs[2]
						      - @unit_price = @net_amount.to_f / @quantity.to_f

							  tr
							    td class="text-right" = listing.purchase.branch.name
							    td class="text-right" = to_default_date_format(listing.purchase.purchase_date)
							    td class="text-right" = listing.purchase.supplier.name
							    td class="text-right" = listing.item.name
							    td class="text-right" = number_with_precision(@quantity, precision: 2)
							    td class="text-right" = number_to_currency(@unit_price, precision: 2, unit: '')
							    td class="text-right" = number_to_currency(@total_purchase_amount, precision: 2, unit: '')
							    - @total_quantity += @quantity.to_f
							    - @total_purchase += @total_purchase_amount
							    - @total_amount += @net_amount
							    - @total_unit_amount += @unit_price

							  tr
							    - if purchase_items.count != 1
							      td colspan="4"
							      - sum = vat_computation_summary(purchase_items)
							      td class="text-right" style="background-color: #DFDFDF;"
							      	b
							       	= number_with_precision(@total_quantity, precision: 2, unit: '')
							      td class="text-right" style="background-color: #DFDFDF;"
							        b
							        	= number_to_currency(sum[2] / @total_quantity , precision: 2, unit: '')
							      td class="text-right" style="background-color: #DFDFDF;"
							        b
							        	= number_to_currency(sum[2], precision: 2, unit: '')
							    - else
							      td colspan="14"

				.align-center
					= will_paginate @purchases, renderer: BootstrapPagination::Rails, previous_label: "←", next_label: "→"

app/views/reports/man_hours.html.slim
.collapse#show-search class="#{ 'in' if params[:q].present? }"
	.panel
		.panel-body
			= form_for man_hours_path, method: 'get' do
				= render 'branch_date_search'

.panel
	.panel-heading.border.pb45
		.pull-left.mt7 Man Hours
	.panel-body
		- if @man_hours.empty?
			.alert.alert-info.text-center role="alert"
				| Oops! There seems to be no records of employee types here.<br> To track employee labour hours: <br> Please go to
				b
					|  Setup > Labor Setup > Employee Type
		- else
			.no-more-tables
				table.table.table-bordered.table-striped.mb0 data-sortable="true"
					thead
						tr.bg-thead
							th Employee Type
							th Total # of Hours
							th Sales
							th Salary Per Man Hour
					tbody
						- @man_hours.each do |man_hour|
							tr
								th = link_to man_hour[:name], "#", class: "view-link", data: { tt: "tooltip", placement: "top", "original-title" => "View Profile" }
								th = man_hour[:hour]
								th = man_hour[:amount]
								th = man_hour[:spmh]

app/views/reports/price_movement_report.html.slim
- content_for :title, "Restobot | Price Movement Report"

= react_component "PriceMovementContainer"

/.panel
/	.panel-heading.border Price Movement Report
/	.panel-body
/		.no-more-tables
/			table.table.table-bordered.table-striped.mb0 data-sortable="true"
/				thead
/					tr.bg-thead
/						th Category
/						th Item
/						th Unit
/						th.hidden Prev
/						th.hidden Curr
/						th Price Movement (₱)
/						th Price Movement (%)
/						th Branch
/						th Created By
/						th Entry Date
/				tbody
/					- previous_amount = 0
/					- @purchase_items.each do |purchase_item|
/						- previous_amount == 0 ? previous_amount = 0 : previous_amount
/						tr
/							td data-title="Category" = purchase_item.item.category.name
/							td data-title="Item" = purchase_item.item.name
/							td data-title="Unit" = purchase_item.unit.name
/							td.hidden = previous_amount
/							td.hidden = current_amount = purchase_item.purchase_item_amount.to_f
/							- upper_amount = current_amount - previous_amount
/							td data-title="Price Movement (₱)"
/							 	- if previous_amount.zero?
/									= '-'
/								- elsif previous_amount > current_amount
/									.price-down
/										i.icon-down-dir.mr5
/										|
/										= upper_amount.abs
/								- else
/									.price-up
/										i.icon-up-dir.mr5
/										|
/										= upper_amount
/							- bottom_amount = (current_amount + previous_amount) / 2
/							td data-title="Price Movement (%)" = previous_amount.zero? ? '-' : to_percentage(upper_amount,bottom_amount)
/							td data-title="Branch" = purchase_item.purchase.branch.name
/							td data-title="Created By" = purchase_item.purchase.created_by.full_name
/							td data-title="Date Created" = purchase_item.created_at.strftime("%B %d %Y")
/							- previous_amount = purchase_item.purchase_item_amount.to_f
/
= render "big_modal"

javascript:
	$(document).ready(function(){
		$("#category_id").on('change', function(){
			$.ajax({
				url: "#{update_item_path}",
				data: {
					category_id: $("#category_id").val()
				}
			});
		});
	});
/ = previous_amount.zero? ? '-' : price_movement(previous_amount,current_amount)

app/views/reports/update_item.js.erb
$('#item_id').html("<%= escape_javascript(options_for_select(@items.pluck(:name, :id))) %>");